### ISSUE TITLE
Request for single Java example

### ISSUE THREAD

**Issue by tanmoysaha3** [kizitonwose/Calendar#369]
I am trying to using this library in java project. For java examples, I completely read the ReadMe and all issues (java related). You said that it is really hard to maintain multiple examples in various languages and I completely agree with that.
But sorry for asking again, can you please only one example in java let's say "Example 1" (no need for documentation)? Since Kotlin is very new to me and many others, one example will help us to understand step by step.
Hope it won't be too hard for you. And thanks again for such a good calendar library.

**Comment by kizitonwose** [comment]
I assume this is no longer needed?
