### ISSUE TITLE
Unexpected space in bottom of month header

### ISSUE THREAD

**Issue by QuarK264** [kizitonwose/Calendar#380]
Hello, @kizitonwose. At first, thank you for the library, it's pretty convenient and flexible.  
Now I am implementing month header for my calendar and faced unexpected space in its bottom, that comes from nowhere.  
<img width="300" src="https://user-images.githubusercontent.com/9616488/179946123-e1adb7d9-b8c4-4f29-b599-35d544b3a77c.jpg" alt="Bug screenshot"/>
I use the following layout for month header:  

    <androidx.constraintlayout.widget.ConstraintLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
    
        <ImageView
            android:id="@+id/previous_month_icon"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:contentDescription="@null"
            android:src="@drawable/ic_arrow_left"
            app:layout_constraintBottom_toBottomOf="@id/month_name"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
    
        <TextView
            android:id="@+id/month_name"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:textAlignment="center"
            android:textAppearance="@style/TextAppearance.Text.Primary.Medium"
            android:textSize="18sp"
            app:layout_constraintEnd_toStartOf="@id/next_month_icon"
            app:layout_constraintStart_toEndOf="@id/previous_month_icon"
            app:layout_constraintTop_toTopOf="parent"
            tools:text="Июль 2022" />
    
        <ImageView
            android:id="@+id/next_month_icon"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:contentDescription="@null"
            android:src="@drawable/ic_arrow_right"
            app:layout_constraintBottom_toBottomOf="@id/month_name"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
    
        <LinearLayout
            android:id="@+id/week_days"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/margin_16dp"
            android:orientation="horizontal"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/month_name">
    
            <TextView
                android:id="@+id/day_one"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:textAlignment="center"
                android:textAppearance="@style/TextAppearance.Text.Primary.Medium"
                android:textSize="16sp"
                tools:text="Пн" />

           
    
            <TextView
                android:id="@+id/day_seven"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:textAlignment="center"
                android:textAppearance="@style/TextAppearance.Text.Primary.Medium"
                android:textSize="16sp"
                tools:text="Пн" />
        </LinearLayout>
    </androidx.constraintlayout.widget.ConstraintLayout>

This space appears after I changed root layout from linear to constraint and added `LinearLayout` for days of the week.

**Comment by QuarK264** [comment]
Today new issue appears: month footer content height is zero, if month has six weeks:
<img width="300" src="https://user-images.githubusercontent.com/9616488/180416228-90cec242-34c1-40c0-855d-f595546c35ab.jpg" /> <img width="300" src="https://user-images.githubusercontent.com/9616488/180416378-5286ef2b-6cf6-45e2-afe0-4d997826f06b.jpg" />
I use `TextView` as layout for footer 

    <TextView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginVertical="@dimen/margin_16dp"
        android:textAlignment="center"
        android:textAppearance="@style/TextAppearance.Text.Secondary"
        android:textSize="14sp" />

I manage to reduce space in month header by using `LinearLayout`s instead of `ConstraintLayout`. Unexpected space is much smaller now, but still exists.

**Comment by kizitonwose** [comment]
Let me know if this is still happening in version [2.0.0](https://github.com/kizitonwose/Calendar/releases/tag/2.0.0)
