### ISSUE TITLE
6th row of a month is shifted to next page when maxRowCount is set to 5

### ISSUE THREAD

**Issue by shining-armour** [kizitonwose/Calendar#390]
Hi @kizitonwose,
I am trying to build a calendar with each month having at most 5 rows. Now, the problem is if a month has more than 6 rows then 
 the last row automatically shifts to the next page making two pages for a single month. I do not want this behavior in my use case since the outDates of the previous month are already visible in the next month. You can easily reproduce this by setting the following attributes for CalendarView in xml layout.

        <com.kizitonwose.calendarview.CalendarView
            android:id="@+id/exOneCalendar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:cv_dayViewResource="@layout/calendar_day"
            app:cv_orientation="horizontal"
            app:cv_scrollMode="paged"
            app:cv_hasBoundaries="true"
            app:cv_maxRowCount="5"
            app:cv_outDateStyle="endOfRow"
            app:cv_inDateStyle="allMonths" />

<img height=500 width=300 src="https://user-images.githubusercontent.com/46320002/191274434-4a8aba93-13c9-48ba-a121-de103477fc22.gif" />

Is there a way to handle this sort of use case or maybe a workaround to skip that extra page while scrolling would also help. On a side note, thanks for this awesome library :)

**Comment by kizitonwose** [comment]
Unfortunately, the property mentioned in this issue is no longer available in the [new version](https://github.com/kizitonwose/Calendar/releases/tag/2.0.0). Kindly update and comment if you still have problems.
