### ISSUE TITLE
Day to day scrolling in week mode

### ISSUE THREAD

**Issue by Greenev** [kizitonwose/Calendar#393]
Hi! I have a calendar in my app much like your one in Example 7, but the difference is that I would like to have center item (there are 5 items on screen) to always be the selected one, so you select another item by scrolling and not by touching
So far so good, but there is a problem, I need "paged" scrolling for every **day**, whereas now it's working like every **week** paging. I want to have an item just in the middle at any time I scroll, is it possible to do so?
P.S. Thanks for your calendar view, it is great!

**Comment by Greenev** [comment]
OK, after spending some time I found where calendar groups days by 7, but it took me much more time to find a good way to introduce this new behavior I've decribed above. I think it seems to be the best to let users attach their own snap helpers, in my case it would be just a recyclerview.widget.LinearSnapHelper. To do so I suggest days might be regrouped by 1 if we are in week mode (maxRowCount = 1) and default ScrollMode.CONTINUOUS is used, please check my PR to see details - https://github.com/kizitonwose/CalendarView/pull/394

**Comment by kizitonwose** [comment]
Unfortunately, the property mentioned in this issue is no longer available in the [new version](https://github.com/kizitonwose/Calendar/releases/tag/2.0.0). Kindly update and comment if you still have problems.
