### ISSUE TITLE
Landscape Mode 

### ISSUE THREAD

**Issue by Paul1886** [kizitonwose/Calendar#397]
Unable to reduce the size of the calendar view  in both month and calendar view while in landscape mode in phone, 
but perfect in portrait,please help

**Comment by kizitonwose** [comment]
What have you tried so far? The view fills the width by default so you may want to specify the width in landscape mode.

**Comment by Paul1886** [comment]
Thanks for the quick reply, And yup its fixed by manually specifying the width in the landscape qualifier.
