### ISSUE TITLE
Want Vertical Scroll on month view to switch to week view and vice versa

### ISSUE THREAD

**Issue by Paul1886** [kizitonwose/Calendar#398]
Hi, I'm trying to implement switching from week view to month view and vice versa on vertical scroll
I implemented the same by using the parent scroll view in  but I want the switching to happen only on scrolling inside the calendar view not on the whole layout. 
Following is my code for implementing my requirement in parent scroll view
Thanks

```
weekCalendarView.isVisible = false
scrollView.setOnScrollChangeListener(View.OnScrollChangeListener { v, scrollX, scrollY, oldScrollX, oldScrollY ->
            val x = scrollY - oldScrollY
            if (x > 0) {
                //scroll down
                //week to month
                monthCalendarView.isVisible = false
                weekCalendarView.requestLayout()
                weekCalendarView.scrollToDate(selectedDate!!)
                weekCalendarView.isVisible = true
            }
            if (x < 0) {
                //scroll up
                //month to week
                    weekCalendarView.isVisible = false
                    monthCalendarView.requestLayout()
                    monthCalendarView.scrollToMonth(selectedDate!!.yearMonth)
                    monthCalendarView.isVisible = true
            }
        })
```

**Comment by kizitonwose** [comment]
If your solution is already working properly but you need it to happen outside the calendar view, then you can:
- set a touch listener on the scroll view.
- when touch down is recorded, check if it is within the bounds of the calendar.
- if it is not, set a variable to `true`, else set it to false.
- In your scroll listener, only toggle week mode if the variable is `true`.

**Comment by Paul1886** [comment]
`when touch down is recorded, check if it is within the bounds of the calendar.`

How do I do this?
Please send some links or example code
I tried searching but was unsuccesful

**Comment by kizitonwose** [comment]
Here's a StackOverflow post discussing how to do this https://stackoverflow.com/a/4692133

**Comment by Paul1886** [comment]
I did as you said and it works as per my requirement, following is the complete code that performs the transition from monthview to weekview
`  val calendar = binding.finalCalendarLayout
        val scrollView = binding.calendarScroll
        
//        var insideCalendarKizton :Boolean = false
        monthCalendarView.visibility = View.VISIBLE

        scrollView?.setOnTouchListener {_, event ->
            if(isPointInsideView(event.getRawX(), event.getRawY(), calendar!!)){
                insideCalendarKizton  = true
                Log.d("kizton",insideCalendarKizton.toString())
            } else
                insideCalendarKizton = false

            false
        }

        scrollView?.setOnScrollChangeListener(View.OnScrollChangeListener { v, scrollX, scrollY, oldScrollX, oldScrollY ->
            val x = scrollY - oldScrollY
            if (insideCalendarKizton){
                if (x > 0)  {
                    //scroll down
                    //week to month
                    weekCalendarView.requestLayout()
                    weekCalendarView.updateLayoutParams {
                        monthCalendarView.visibility = View.GONE
                        weekCalendarView.requestLayout()
                        weekCalendarView.scrollToDate(selectedDate!!)
                        weekCalendarView.visibility = View.VISIBLE
                        weekCalendarView.requestLayout()
                    }
                }
                if (x < 0)
                {
                    //scroll up
                    //month to week
                    monthCalendarView.requestLayout()
                    monthCalendarView.updateLayoutParams { weekCalendarView.visibility = View.GONE
                        monthCalendarView.requestLayout()
                        monthCalendarView.scrollToMonth(selectedDate!!.yearMonth)
                        monthCalendarView.visibility = View.VISIBLE
                        monthCalendarView.requestLayout() }
                }
            }
        })`

But without the update layout params and the animations because without them the layout sometimes doesn't update and is causing glitches during transition.
I need help integrating the update layout params and animations for above code.

**Comment by kizitonwose** [comment]
There are some things wrong in your code like setting view visibility, and calling `scrollToMonth()` inside `updateLayoutParams()`. You have to figure out what you are not doing right. The previous discussions should guide you as I cannot provide specific help without access to the app code to see what exactly is happening.
