### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by Paul1886** [kizitonwose/Calendar#399]
In landscape mode is there anyway I can make the month view look like in the screenshot?
I tried adjusting the width
![IMG_7CE4E86539D4-1](https://user-images.githubusercontent.com/70909043/197136266-6ce4c02a-fa4c-44b6-bade-b36001f2182e.jpeg)

**Comment by kizitonwose** [comment]
What version are you on? Also, view/compose?

**Comment by Paul1886** [comment]
Version 2 latest, calendar view

**Comment by kizitonwose** [comment]
The default behavior is square for the day cells. You need to change the `daySize` property to `SeventhWidth` for landscape mode, then you can set a custom height for the cells, for example, `screen height / 6`. You can do this in the `MonthDayBinder` when `create` is called.

**Comment by Paul1886** [comment]
Screenshot of my progress after selecting SeventhWidth for landscape mode, now is there any way i can crop selected day background? Its a rounded square in portrait mode
![Screenshot_2](https://user-images.githubusercontent.com/70909043/197236036-103d559c-8faf-4db8-9117-07710d471e9b.png)

**Comment by Paul1886** [comment]
Bro I fixed it finally, I didnt use the SquareView as it set the width according to the height and for single digit date values it looked bad, So this is my day.xml

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:gravity="center">

    <TextView
        android:layout_margin="@dimen/_1sdp"
        android:paddingTop="@dimen/_5sdp"
        android:paddingBottom="@dimen/_5sdp"
        android:id="@+id/tv_day_text"
        android:textAlignment="center"
        android:layout_width="@dimen/_28sdp"
        android:layout_height="wrap_content"
        style="@style/calendar_day_theme"
        android:fontFamily="@font/roboto"
        tools:text="22" />
</LinearLayout>
```

I learnt a lot in the process of fixing the landscape view bro thanks a lot for all your help.
If I need any more help I'll reach out.

![Screenshot_Final_cropped](https://user-images.githubusercontent.com/70909043/197330428-85c7ffc1-d75e-4cd9-8edd-14e488cfcf87.png)

**Comment by kizitonwose** [comment]
Glad you got it working 🎉  Will close this issue now.
