### ISSUE TITLE
Is it possible to change the calendar to a monthly calendar by scrolling vertically in the calendar view?

### ISSUE THREAD

**Issue by LeeYoungki** [kizitonwose/Calendar#407]
Hi! I am a Korean developer.
First of all, thank you for providing a powerful library. I support your powerful library in Korea.

I'm making a calendar in the same form as Example 1.
However, the difference is that I am making a calendar view that can be expanded or reduced by vertical scrolling.
In other words, I am making something that can change the week mode and month mode through vertical scrolling.

Currently, the vertical scroll is detected and the mode is changed using the CalendarView.setOnTouchListener.
The first problem with this method is poor usability, and the second problem is that it overlaps with the horizontal scroll and does not recognize the vertical scroll properly.

The best case I want is to change the mode according to the touch, is there any way?

The attached video is a calendar made by my friend, iPhone developer.

Thank you for reading the short question!
I'm sorry that there's a possibility that the translation is bad!

https://user-images.githubusercontent.com/16497890/198889967-4de0b3b0-8b56-422c-86e8-2e0ef2005472.mp4

**Comment by kizitonwose** [comment]
There was a recent discussion here #398 maybe something in that thread helps you?

**Comment by LeeYoungki** [comment]
Great! Your answer was helpful to me. Thank you.

I have a question about performance when changing the mode
Can I ask you one more question?
Or is it better to post a new post?

**Comment by mani-js** [comment]
Hi same thing I wanted to achieve for compose calendar
