### ISSUE TITLE
CoreLibraryDesugaring configuration error

### ISSUE THREAD

**Issue by baonq-2356** [kizitonwose/Calendar#409]
I am trying use this library in Android 12, I use latest version of `implementation 'com.kizitonwose.calendar:view:<latest-version>'` is `2.0.0` and trying different version of `'com.android.tools:desugar_jdk_libs:<latest-version>'` is `2.0.0`, `1.2.2` and `1.0.9`. Unfortunately, I get this error in all case when I build app:
` coreLibraryDesugaring configuration contains no dependencies. If you intend to enable core library desugaring, please add dependencies to coreLibraryDesugaring configuration.`
Anyone have solution?

**Comment by kizitonwose** [comment]
The library uses desugar_jdk_libs  version `1.1.8`, can you try that?

**Comment by kizitonwose** [comment]
Also, hopefully, you are using this `coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.8` in the `dependencies` block.

**Comment by baonq-2356** [comment]
Ohh, I found the problem is `minSdkVersion`. Currently, I use `minSdkVersion` is 26, so step 1 can be ignore. This problem resolved.
Thank you so much for your support @kizitonwose
