### ISSUE TITLE
Any Swift UI or other alternatives for iOS

### ISSUE THREAD

**Issue by L3K0V** [kizitonwose/Calendar#411]
Hey @kizitonwose,

I really love this library! I'm working on some projects which have Android and iOS apps.
Do you know or have you played with any similar libraries which can be used for iOS and Swift UI? 
Do you have plan porting this to Swift UI?

Thanks!

**Comment by kizitonwose** [comment]
https://github.com/patchthecode/JTAppleCalendar is a very good iOS calendar library that I have used in the past before I created this for Android. No SwitUI support in the lib AFAIK.

**Comment by kizitonwose** [comment]
I guess this can be closed, feel free to reopen/comment to continue the discussion.
