### ISSUE TITLE
How to improve calendar render performance?

### ISSUE THREAD

**Issue by LeeYoungki** [kizitonwose/Calendar#412]
### Library information:
 - Version: 1.1.0
 - View or Compose module: View

### Question:
Please tell me how I can improve my performance by improving my logic.

Hi. I'm a Korean developer who came yesterday!
First of all, thank you for providing a powerful library. I support your powerful library in Korea.

This is an explanation of my logic.
1. Import data to be drawn on the calendar by API call.
2. Initialize what is needed (DayBinder, monthScrollListener etc..) )
3. UpdateMonthConfiguration() -> setupAsync() -> scrollToDate() call to default setting of calendar
4. When scrollToDate() is completed, bind() is called, addOnScrollListener is called, and monthScrollListener is called.
5. The inside of Class DayBinder.bind() sets the data in the following order.
6. Date setting in TextView.text
7. imageView Visible, Gone to output on-offable icons to display on the calendar.
8. Set the date text for DayOwner.THIS_MONTH and other things
9. CoroutineScope(Dispatchers.Default).Launch{} for draw icons on the calendar as data.
10. in forEach, using withContext(Dispatchers.Main) for set visible -> for icon render on calendar
11. Rendering icon using forEach total 3 times 
12. It is executed in this way. Whenever swiping left and right, the API is called inside the monthScrollListener and executed in the order of 1 to 10 to render the calendar.

Like the issue I posted yesterday, I want to change the row of the calendar with vertical scrolls!
I want to see a calendar that unfolds without performance issues.

I want you to help me!

I also upload code snippets in case you don't understand the questions due to the translation quality.

```
override fun bind(container: DayViewContainer, day: CalendarDay) {
    container.day = day // for dayView.setOnClickListener{}
    container._binding.apply {
        calendarDayText.text = day.date.dayOfMonth.toString()

        // setting View's Gone
        mainWalkIconView.beGone()
        subWalkIconView.beGone()
        subWalkIconView2.beGone()
        subWalkIconView3.beGone()
        vaccineImageView.beGone()
        groupImageView.beGone()

        if (historyCalendarView.maxRowCount != 1) {
            if (day.owner == DayOwner.THIS_MONTH) {
                calendarDayText.setTextColor(
                    getColor(
                        context,
                        R.color.font_black
                    )
                )
            } else {
                calendarDayText.setTextColor(
                    getColor(context, R.color.font_light_gray)
                )
            }
        }

        val rowCnt = historyCalendarView.maxRowCount
        CoroutineScope(Dispatchers.Default).launch {
            walkListForDaySetting.forEach { item ->
                if (item.walkDate == day.date.toString()) {
                    if (day.owner == DayOwner.THIS_MONTH) {
                        withContext(Dispatchers.Main) {
                            // setting icon View Visible & View BackgroundTint Color
                            mainWalkMarker.beVisible()
                            mainWalkMarker.backgroundTintList =
                                ColorStateList.valueOf(
                                    ContextCompat.getColor(
                                        requireContext(),
                                        colorList[user]
                                    )
                                )

                            // ... sub Views Setting

                        }
                    }
                }
            }
            if (rowCnt != 1) {
                if (day.owner == DayOwner.THIS_MONTH) {
                    vaccineListForDaySetting.forEach { item ->
                        if (item.vaccineDate == day.date.toString()) {
                            withContext(Dispatchers.Main) {
                                vaccineImageView.beVisible()
                            }
                        }
                    }

                    assembleListForDaySetting.forEach { item ->
                        if (item.groupDate == day.date.toString()) {
                            withContext(Dispatchers.Main) {
                                groupImageView.beVisible()
                            }
                        }
                    }
                }
            }
        }
    }
}

```

**Comment by kizitonwose** [comment]
Doing any sort of work in onBind() is a bad idea as this will be called for each day in the month (approx 30!), you can use the calendar scroll listener and load the data then call `notifyMonthChanged()` so the bind will be called again and you can use the data. The idea is based on how RecyclerView works.

**Comment by LeeYoungki** [comment]
I didn't exactly understand the guide you told me. 
I only do drawing in `bind()`.

When `monthScrollListener` is called, it is understood that `bind()` is called for rendering next month (or previous month). 
So I call the API for importing data from `monthScrollListener` next month. 
When the API receives the result data, it calls `notifyCalendarChanged()`. The reason why it is not `notifyMonthChanged()` is that you also need to draw icons on inDates and outDates.

I mean, in bind(), only the visible and Gone processing of View for drawing and color setting.

What should I improve on?

**Comment by kizitonwose** [comment]
Hi, I see you are launching coroutines in the bind function, you should not do that. Anyway, I'm sorry but you have to figure out what you are not doing right, It is hard for me to provide suggestions without having the full source code to figure out what is going on. Kindly read the documentation to better understand the available properties. I will close this issue.
