### ISSUE TITLE
How to make DaySize, so that width and height max out the view size?

### ISSUE THREAD

**Issue by TIMBLOCKER** [kizitonwose/Calendar#414]
### Library information:
 - Version: 2.0.0
 - I'm using the View Module.

Hello Kitzito,
i really love your library and it helped me a lot to accomplish my goals.
But I can't really figure out, how to make the DaySize of each day, so that everything evenly spaces out.

I tried using the `daySize:seventhWidth` property, but it only spaces widthwise. I'd like to make a Calendar, that also spaces out heightwise automatically. To make things easier im using the `endofGrid` and `scrollPaged=true` property to make the pages even in every month. I only need to make the days fit to the screensize devided by 7 in width and by 6 in height. 

Any help or idea would be much appretiated. 

![Concept of Calendar](https://user-images.githubusercontent.com/71724235/200123865-4637bbd2-79ac-4025-bb74-eec813cafaab.png)

This is the Concept that comes to my mind. One would swipe from left to right to see the pages...

**Comment by kizitonwose** [comment]
Hey, there is a new snapshot deployed with this feature:

In your project build.gradle file:

```groovy
    repositories {
        google()
        mavenCentral()
        maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots/' }
    }
```

In your app build.gradle:
`implementation "com.kizitonwose.calendar:view:2.0.2-SNAPSHOT"`

There is a new daySize option: `rectangle`, if this is set and the calendarview's width and height are `match_parent`, you'd get the full-screen calendar.

Here's example 1 with this configuration:

<img src="https://user-images.githubusercontent.com/15170090/200185288-406a55a4-869d-46ed-8fb5-5d4c5af25d40.png" width="300">

This feature is not final, but with your help testing it, I can ship it in the coming days.

**Comment by TIMBLOCKER** [comment]
Hey Kitzito,
you are awesome! I couldn't have even imagined how fast you made this solution.
It works perfectly. Now evetything spaces out evently.

![Screenshot_20221106-193751_Mein HSW Stundenplan](https://user-images.githubusercontent.com/71724235/200189021-94b76d01-832c-44de-abe9-9c6dc8ed0c4f.jpg)
This is a quick demo I put together.

Note:
For everyone who wants to follow the implementation of the snapshot until the new version is issued:

Using the latest Android Studio (DOLPHIN) causes problems with the `sonatype` repo.
Just add the `maven {url}` not only in the `buildscripts `of the `build.gradle(project)` but also in `settings.gradle` under `repositories` in `pluginManagement` and  `dependencyResolutionManagement`. If done so, Android Studio recognizes the sonatype repo correctly.

All in all:
Thanks Kitzito for the quick response, which has gotten farely common with all issues in your library. We need more open-source devs like you. People that care about their libaries and the people who use them.

You rock!

PS: If you need anything specific in testing from me. Just get in touch. I can then help you push out the fix ASAP.

**Comment by kizitonwose** [comment]
Hey, thanks for the kind words. I am glad that the update works as expected. I will now do some final checks on my end and also add some UI tests for this behavior and the release will be published. Keep an eye out for the next version - hopefully between now and the weekend.
