### ISSUE TITLE
Can't find com.kizitonwose.calendar.sample.databinding.

### ISSUE THREAD

**Issue by EmperoRRx** [kizitonwose/Calendar#416]
### Library information:
 - Version: [e.g. 2.0.0]
 - View or Compose module: [e.g. View]

### Question:
Hi, I can't find calendar.sample.databinding folder in given path. There are only 3 folders and main. It is first time that I use github so sorry for this stupid question.

**Comment by kizitonwose** [comment]
This is created locally when you build the project and used by [ViewBinding](https://developer.android.com/topic/libraries/view-binding). It is not included in source control.
