### ISSUE TITLE
Current date not selected

### ISSUE THREAD

**Issue by Otang45** [kizitonwose/Calendar#419]
Help today date not auto selected![Screenshot_2022-11-16-15-04-16-280_com.tyron.code.jpg](https://user-images.githubusercontent.com/55321267/202122356-9f74a961-10e8-4477-bd0d-e11b1d1f0dfe.jpg)![Screenshot_2022-11-16-15-02-15-930_otang.calendar.jpg](https://user-images.githubusercontent.com/55321267/202122402-f9676391-4ffd-45c7-8e9e-6aee7300e4a4.jpg)

**Comment by kizitonwose** [comment]
Your logic looks right, can I see the xml for the day view?

**Comment by Otang45** [comment]
Sorry my project has been deleted 😅, i forgot not backup
