### ISSUE TITLE
Layout of Day View is Cut

### ISSUE THREAD

**Issue by diofelpallega** [kizitonwose/Calendar#420]
### Library information:
 - Version: 1.4.0
 - View 

### Describe the bug**
I'm trying to build a week view calendar with an image below the day TextView such that the day container view has height greater than it's width. When the calendar renders the UI, the image under the dat TextView is cut. I saw that it's default set to a square size. Is there a way for the tile height to be set as wrap content instead?

### To Reproduce (if applicable)

1. Add a long vertical image below day container layout under day text view
2. load UI
4. See image under day text view is cut

### Expected behavior (if applicable)
The image view under the text shoudn't be cut or the calendar week view should allow long day container layout not just square layouts

### Screenshots? (if applicable)
If applicable, add screenshots or screen recordings to help explain the problem.

![test](https://user-images.githubusercontent.com/8383174/202234043-344f40b2-6dca-47c4-820b-9b698de79fb1.jpg)

### Additional information
Add any other information about the bug here.

**Comment by kizitonwose** [comment]
You need to set the `daySize` property to `CalendarView.sizeAutoWidth(yourHeight)`

**Comment by diofelpallega** [comment]
Thanks @kizitonwose  it worked :D!
