### ISSUE TITLE
Compose continuous vertical calendar without `outDates`

### ISSUE THREAD

**Issue by L3K0V** [kizitonwose/Calendar#424]
### Library information:
 - Version: 2.0.4
 - View or Compose module: Compose

### Describe the bug**

Following the Compose documentation but replacing the horizontal calendar with a vertical one I got this strange behaviour.
**I'm not able to have continuous calendar and disable `outDates`**

### To Reproduce (if applicable)

```kotlin
val currentMonth = remember { YearMonth.now() }
val startMonth = remember { currentMonth.minusMonths(100) } // Adjust as needed
val endMonth = remember { currentMonth.plusMonths(100) } // Adjust as needed
val daysOfWeek = remember { daysOfWeek() }
var selectedDate by remember { mutableStateOf<LocalDate?>(null) }

val calendarState = rememberCalendarState(
    startMonth = startMonth,
    endMonth = endMonth,
    firstVisibleMonth = currentMonth,
    firstDayOfWeek = daysOfWeek.first(),
    outDateStyle = OutDateStyle.EndOfGrid
)

...

Column {
    DaysOfWeekTitle(daysOfWeek = daysOfWeek)
    VerticalCalendar(
        state = calendarState,
        dayContent = { day ->
            Day(day, isSelected = selectedDate == day.date) { day ->
                selectedDate = if (selectedDate == day.date) null else day.date
            }
        },
        monthHeader = {
            Text("New Month")
        }
    )
}
```

### Expected behavior (if applicable)

For vertical calendar to be able to configure it as continuous. If there is month header to be able to not show the out dates.

### Screenshots? (if applicable)

![image](https://user-images.githubusercontent.com/2267270/204093459-53b0bd03-6731-4e12-8b2c-a39028b948d0.png)

### Additional information

@kizitonwose can you help me here? I think it is something related with the processing the days and should be checked if they are in the new month or not, but I'm not sure. Maybe a documentation update will be nice to have for such basic usages.

**Comment by kizitonwose** [comment]
You need to use `OutDateStyle.EndOfRow` so the extra row is not generated.

```kotlin
val calendarState = rememberCalendarState(
    startMonth = startMonth,
    endMonth = endMonth,
    firstVisibleMonth = currentMonth,
    firstDayOfWeek = daysOfWeek.first(),
    outDateStyle = OutDateStyle.EndOfRow // You can also just remove the parameter since EndOfRow is the default value.
)
```

**Comment by L3K0V** [comment]
![image](https://user-images.githubusercontent.com/2267270/204095248-922d16c7-0077-45db-95ce-f47a0f633e9f.png)

I suppose now if I want to not show some out or in dates this must be handled in the Day component?

**Comment by L3K0V** [comment]
Done! I continue with the customisations now!
