### ISSUE TITLE
Persian Calendar

### ISSUE THREAD

**Issue by xmha97** [kizitonwose/Calendar#425]
Thanks for creating this component.
Please add support "Persian Calendar".
Thanks.

**Comment by kizitonwose** [comment]
Hey, thanks for creating this issue. However, I do not know enough about the Persian Calendar system to implement it. There's a fork of the library with this feature, you can find it [here](https://github.com/sma6871/CalendarView)

**Comment by xmha97** [comment]
Thank you and you can close this issue, but if it was possible to add the changes to the main project, it would be much better.
