### ISSUE TITLE
Updating CalendarState.firstDayOfWeek does not change UI

### ISSUE THREAD

**Issue by hscissors** [kizitonwose/Calendar#429]
### Library information:
 - Version: 2.1.0
 - View or Compose module: Compose

### Describe the bug**
We have a `val calendarState = rememberCalendarState()` where the first day is set to `Sunday`. If we change it during run time, the ui does not update. We tried calling `calendarState.firstDayOfWeek = Monday` but it does nothing.

**Comment by kizitonwose** [comment]
Released [2.1.1](https://github.com/kizitonwose/Calendar/releases/tag/2.1.1) with this fix today 🎉
