### ISSUE TITLE
After generate Release sign api  Calenderview.setup function throw error

### ISSUE THREAD

**Issue by KjMithawala** [kizitonwose/Calendar#432]
### Library information:
 - Version:2.0.4
 - View or Compose module:  calenderview.setup(startMonth, endMonth, SUNDAY);

### Describe the bug**
when i set the calenderview with start month and end month  and day of week it will  work fine on debugable application but once i generated sign apk it was not work and throw error 

Fatal Exception: java.lang.NoSuchMethodError
No virtual method between(Lj$/time/temporal/Temporal;Lj$/time/temporal/Temporal;)J in class Lj$/time/temporal/ChronoUnit; or its super classes (declaration of 'j$.time.temporal.ChronoUnit' appears in /data/app/~~iLExDRd_EWQEtJRSVe7vRg==/com.plapdc.production-L1BjoCyZD5U8Yv-KGydiVA==/base.apk!classes2.dex)

com.kizitonwose.calendar.data.MonthDataKt.getMonthIndex (MonthData.kt:87)
com.kizitonwose.calendar.data.MonthDataKt.getMonthIndicesCount (MonthData.kt:92)
com.kizitonwose.calendar.view.internal.monthcalendar.MonthCalendarAdapter.<init> (MonthCalendarAdapter.kt:39)
com.kizitonwose.calendar.view.CalendarView.setup (CalendarView.kt:401)

this all were error logs

**Comment by kizitonwose** [comment]
Hey, could you kindly provide a sample APK with which I can reproduce this issue? Thanks.

**Comment by KjMithawala** [comment]
Its implemented on my project you can create your repo sign apk and it will  affect you  same

**Comment by kizitonwose** [comment]
I use the library in two projects and do not have this issue with the release build.

**Comment by KjMithawala** [comment]
Issue Resolved 
Its conflicted with my project library version 
After Updating Compilesdk targetsdk and all  library version to latest one  problem solved 
Thank you

**Comment by kizitonwose** [comment]
Glad to hear that the issue is resolved.
