### ISSUE TITLE
Calendar Events Not Saving

### ISSUE THREAD

**Issue by gusterfan2180** [kizitonwose/Calendar#434]
### Library information:
 - Version: 2.0.0
 - View or Compose module: View

### Question:
I created some custom Events for the end-user to use via a custom Alert Dialog. I see the events saving initially, but when I close out of the Calendar and come back in, the events are gone. I am relatively new to Kotlin programming, so I am sure I am missing something with making sure the UUID events are able to be accessed on a new instance of the application. Do you have any ideas on what I should look at?

I am able to provide any code you need, but the main things I changed from the stock code were the custom Alert dialog and the visual aspects.

**Comment by kizitonwose** [comment]
The library does not have any storage logic included, you have to store any events in your repository or somewhere and reflect those events on the calendar. The logic for this is not included in the library.
