### ISSUE TITLE
I can't show calendar title.

### ISSUE THREAD

**Issue by NurayYnlmz** [kizitonwose/Calendar#435]
I'm trying to make the calendar in example 7 but I can't print the month and year in the header.
In your example, your getWeekPageTitle code is not writing in my project.

Binding.exSevenCalendar.weekScrollListener ={ weekDays ->
Binding.exSevenToolbar.title=getWeekPageTitle(weekDays)

**Comment by kizitonwose** [comment]
Can you verify that the week scroll listener is actually called when you swipe the calendar? 
Also, do you have the `scrollPaged` property set to `true` on the calendar?

**Comment by NurayYnlmz** [comment]
Yes I have the scrollPaged property set to true in the calendar.

**Comment by kizitonwose** [comment]
> Can you verify that the week scroll listener is actually called when you swipe the calendar?

What about this?

**Comment by NurayYnlmz** [comment]
> > Can you verify that the week scroll listener is actually called when you swipe the calendar?
> 
> What about this?
Yes I looked.

**Comment by kizitonwose** [comment]
Sorry, I don't follow. Is the listener called on each scroll?

**Comment by NurayYnlmz** [comment]
> Sorry, I don't follow. Is the listener called on each scroll?
Yes

**Comment by kizitonwose** [comment]
Then all you have to do is use the provided date in the listener to update the UI, as shown in the examples.

**Comment by NurayYnlmz** [comment]
Thanks for your help. I found my mistake and fixed it.

**Comment by kizitonwose** [comment]
Glad to hear that the issue is resolved.
