### ISSUE TITLE
How I can change language of month title to local 

### ISSUE THREAD

**Issue by AndresHdz99** [kizitonwose/Calendar#436]
I'm trying to make the calendar but I can't print the month in language local, use the example 1 

Code
val month = binding.calendarView.findFirstVisibleMonth()?.yearMonth ?: return
binding.exOneMonthText.text = month.month.displayText(short = false)

how would i implement it??
I need the month to be displayed in another language

**Comment by kizitonwose** [comment]
This is the logic:

```kotlin
fun Month.displayText(short: Boolean = true): String {
    val style = if (short) TextStyle.SHORT else TextStyle.FULL
    return getDisplayName(style, Locale.ENGLISH)
}
```

You can change `Locale.ENGLISH` in the code to the desired locale.
