### ISSUE TITLE
 animateScrollToWeek  

### ISSUE THREAD

**Issue by eliomaroun** [kizitonwose/Calendar#437]
### Library information:
 - Version: [e.g. 2.0.0]
 - View or Compose module: [e.g. View]

### Question:
I am using animateScrollToWeek and if I swipe to a new week it returns me to the current selectedDate, if i swipe for past weeks there is no problem. How to solve it?
```


@Composable
fun WeekCalendarView(
    onSelectedDate: LocalDate,
    onSelectDate: (LocalDate) -> Unit
) {

    var selectedDate by remember { mutableStateOf(onSelectedDate) }
    val currentDate = remember { LocalDate.now() }
    val startDate = remember { currentDate.minusDays(750) }
    val endDate = remember { currentDate.plusDays(750) }
    val daysOfWeek = remember { daysOfWeek(firstDayOfWeek = DayOfWeek.MONDAY) }
    val coroutineScope = rememberCoroutineScope()
    Column(
        modifier = Modifier
            .background(Color.White)
            .padding(8.dp),
    ) {
        val state = rememberWeekCalendarState(
            startDate = startDate,
            endDate = endDate,
            firstVisibleWeekDate = onSelectedDate,
            firstDayOfWeek = daysOfWeek.first()
        )
        Text(text = state.firstVisibleWeek.days.first().date.month.toString())
        WeekCalendar(
            state = state,
            dayContent = { day ->
                DayWeek(day.date, isSelected = onSelectedDate == day.date, onClick = {
                    selectedDate = it
                    onSelectDate(selectedDate)
                })
            }
        )
        coroutineScope.launch { state.animateScrollToWeek(onSelectedDate) }
    }
}
```

**Comment by kizitonwose** [comment]
The scroll action is performed on each recomposition. You should use a `LauchEffect` if you need to scroll initially.

However, I do not think you need to scroll on each click since the user is already on the clicked page.

**Comment by eliomaroun** [comment]
[I added a boolean to test when I should animate
](url)
@Composable
fun WeekCalendarView(
    onSelectedDate: LocalDate,
    onSelectDate: (LocalDate) -> Unit,
    goToChangedDateAnimation: Boolean
) {

    var selectedDate by remember { mutableStateOf(onSelectedDate) }
    val currentDate = remember { LocalDate.now() }
    val startDate = remember { currentDate.minusDays(750) }
    val endDate = remember { currentDate.plusDays(750) }
    val daysOfWeek = remember { daysOfWeek(firstDayOfWeek = DayOfWeek.MONDAY) }
    val coroutineScope = rememberCoroutineScope()
    Column(
        modifier = Modifier
            .background(Color.White)
            .padding(8.dp),
    ) {
        val state = rememberWeekCalendarState(
            startDate = startDate,
            endDate = endDate,
            firstVisibleWeekDate = onSelectedDate,
            firstDayOfWeek = daysOfWeek.first()
        )
        Text(text = state.firstVisibleWeek.days.first().date.month.toString())
        if (goToChangedDateAnimation) coroutineScope.launch { state.animateScrollToWeek(onSelectedDate) }
        WeekCalendar(
            state = state,
            dayContent = { day ->
                DayWeek(day.date, isSelected = onSelectedDate == day.date, onClick = {
                    selectedDate = it
                    onSelectDate(selectedDate)
                })
            }
        )
    }
}

**Comment by kizitonwose** [comment]
Not the ideal approach IMO, but glad it works for you 🎉  Will close this issue.
