### ISSUE TITLE
calendar.scrollToDate(localDate) is not working when switching to a long range date.

### ISSUE THREAD

**Issue by mostafaimran** [kizitonwose/Calendar#438]
`calendar.scrollToDate(localDate)` works for small-range dates but fails for long-range dates.

Suppose, I am on January 2023 and switching the calendar view to January 2090. Then the scroll doesn't work and `calendar.monthScrollListener` doesn't get called.  
It works for small distant dates only, when long distant dates are used then it fails.

Can anyone give a solution to this?

**Comment by kizitonwose** [comment]
Can you confirm that you have the target date included in the setup range?

**Comment by mostafaimran** [comment]
Thanks. It worked when the setup range is increased.
