### ISSUE TITLE
Select today's date

### ISSUE THREAD

**Issue by pntbiz-leeminhyeok** [kizitonwose/Calendar#439]
### Library information:
 - Version: 2.0.0
 - View or Compose module: View

### Question:
Hello, I'm an Android developer in Korea. Today is January 10th. I want to choose January 10th again if I press that green button after choosing another day. What should I do?
![Screenshot_20230110-161557](https://user-images.githubusercontent.com/114632143/211486445-938d8abe-2418-4d5f-ac28-7b286e78a6c0.png)

**Comment by kizitonwose** [comment]
This would be the order of action:

1. Green button is pressed.
2. Replace `4` with LocaDate.now() in the field/repository where the selected date is saved.
3. Call caledarView.notifyDateChanged() with the old date (4) and the new date (now) to refresh the UI.

I think it would be the same logic as the date selection except that you provide the desired date in this case.
