### ISSUE TITLE
Snap behavior customization

### ISSUE THREAD

**Issue by ArturSechko** [kizitonwose/Calendar#440]
Version: 2.1.1 Compose

Hi! Great library.

I'm using HorizontalCalendar composable and want to change snap fling behavior. I want fling gesture to change one month at most. Right now it is possible to swipe through a whole  year with one gesture. Is it possible to change?

**Comment by kizitonwose** [comment]
Set the `calendarScrollPaged` property to `true`.

```kotlin
HorizontalCalendar(
    calendarScrollPaged = true
)
```

**Comment by kizitonwose** [comment]
Oh, I see. I am already considering making the fling behavior a property of the composable. This will likely be included in the next release but I cannot provide a timeline for that at the moment.

**Comment by ArturSechko** [comment]
Seems relatable https://github.com/kizitonwose/Calendar/issues/445

**Comment by kizitonwose** [comment]
The fix for the underlying issue is out, so I am not sure if I still want to expose the underlying snap behavior as that would require exposing the internal LazyList state. I'll close this for now and see if more people need this in the future.
