### ISSUE TITLE
ImageResource Update Issue

### ISSUE THREAD

**Issue by gusterfan2180** [kizitonwose/Calendar#441]
### Library information:
 - Version: 2.0.0
 - View

### Question:
How do I update the imageResource for a specific day based on the event saved to the day?

**Comment by dgudim** [comment]
I am not the author of the lib, but i think I can answer that. If you want to display event indicators on days just put them into your `cv_dayViewResource` view and set their color/hide them in the `bind method` of the `dayBinder`, you have access to `CalendarDay` there so you can get your events from a list saved somewhere. 

The whole example would look something like this
```java
calendarView.setDayBinder(new MonthDayBinder<CalendarDayViewContainer>() {
    @NonNull
    @Override
    public CalendarDayViewContainer create(@NonNull View view) {
        return new CalendarDayViewContainer(CalendarDayLayoutBinding.bind(view), CalendarView.this);
    }
            
    @Override
    public void bind(@NonNull CalendarDayViewContainer container, CalendarDay calendarDay) {
        container.bindTo(calendarDay, CalendarView.this);
    }
});
```

And in the `bindTo`
```java
public void bindTo(CalendarDay elementDay, CalendarView calendarView) {
    date = elementDay.getDate();
    binding.calendarDayText.setText(String.format(Locale.getDefault(), "%d", date.getDayOfMonth()));
    
    DayPosition dayPosition = elementDay.component2();
    
    // highlight current date
    if (datesEqual(date, calendarView.selectedDate) && dayPosition == DayPosition.MonthDate) {
        binding.root.setBackgroundResource(R.drawable.round_bg_calendar_selection);
    } else {
        binding.root.setBackgroundResource(0);
    }
}
```


P.s: apologies to [kizitonwose](https://github.com/kizitonwose) if the example is bad

**Comment by gusterfan2180** [comment]
Thanks for the help! I am trying to update the imageView based on the event that is saved to the day. For example, if event = red, make the imageView the red image, if event = blue, make the imageView the blue image, etc.

**Comment by gusterfan2180** [comment]
I will look into this. Since I am using Kotlin, and still learning a little, I am still trying to translate what you came up with and figure out how to add it into my project.

**Comment by gusterfan2180** [comment]
I am able to get the Day views to show an image, but when the CalendarView loads, all days that have any event show the same image (the image from the last event that was loaded.) If I select each day that has the 'wrong' image and then select a different day, the 'right' image then shows. Here is the logic I have for loading the events from Room and for the Binding:

 for (item in allEvents) {

            println("currentIssueType eventType --------------------------------> ${item.eventType}")

            val currentDate = item.date
            val currentIssueType = item.eventType
            val id = item.id

            loadEvent(id, currentDate, currentIssueType)
        }

    private fun loadEvent(id: Int, currentDate: LocalDate, currentEventType: String) {
        val id = id
        val currentDate = currentDate
        val currentEventType = currentEventType
        selectedDate = currentDate
        viewModel.addNewEvent(id, currentDate, currentEventType)
        saveEvent(currentEventType)
        binding.viewCalendar.notifyDateChanged(currentDate)
        println("loadEvent eventType --------------------------------> $currentEventType")
    }

binding.viewCalendar.dayBinder = object : MonthDayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)
            override fun bind(container: DayViewContainer, data: CalendarDay) {
                container.day = data
                val textView = container.binding.calendarDayText
                newEvent?.date
                var eventEventType = eventType
                val dotView = container.binding.exThreeDotView

                textView.text = data.date.dayOfMonth.toString()

                if (data.position == DayPosition.MonthDate) {
                    textView.makeVisible()
                    when (data.date) {
                        today -> {
                            textView.setTextColorRes(R.color.example_3_white)
                            textView.setBackgroundResource(R.drawable.day_today_bg)
//                            dotView.makeInVisible()
                        }
                        selectedDate -> {
                            textView.setTextColorRes(R.color.colorPrimaryDark)
                            textView.setBackgroundResource(R.drawable.day_selected_bg)
                            dotView.makeInVisible()
                        }
                        else -> {
                                when (eventEventType) {
                                    "Red" -> {
                                        dotView.setImageResource(R.drawable.day_light_bg)
                                        eventEventType = ""
                                    }
                                    "Blue" -> {
                                        dotView.setImageResource(R.drawable.day_blue_bg)
                                        eventEventType = ""
                                    }
                                    "Green" -> {
                                        dotView.setImageResource(R.drawable.day_green_bg)
                                        eventEventType = ""
                                    }
                                    "Small Green" -> {
                                        dotView.scaleType = ImageView.ScaleType.CENTER_INSIDE
                                        dotView.setImageResource(R.drawable.day_green_bg)
                                        eventEventType = ""
                                    }
                                    "Start" -> {
                                        dotView.setImageResource(R.drawable.day_start_bg)
                                    }
                                    "Future" -> {
                                        dotView.setImageResource(R.drawable.day_future_bg)
                                    }
                                }
                                textView.setTextColorRes(R.color.example_3_black)
                                textView.background = null
                                dotView.isVisible = events[data.date].orEmpty().isNotEmpty()
                            }
                    }
                } else {
                    textView.makeInVisible()
                    dotView.makeInVisible()
                }
            }

**Comment by dgudim** [comment]
You probably have to refresh the calendar after you have added all the events instead of doing it like this: `binding.viewCalendar.notifyDateChanged(currentDate)` If you publish the full project somewhere I can probably offer better help because this wall of code doesn't really tell me much. You can also check out my usage of the lib: [HERE](https://github.com/dgudim/Scheduler/blob/master/app/src/main/java/prototype/xd/scheduler/views/CalendarView.java)

**Comment by gusterfan2180** [comment]
I tried calling notifyMonthChanged() after all the events are loaded and nothing changed. I just need to know the proper methods to load an event from Room and show it on the calendar day. I am successful in making it work for any new event I enter, but as soon as the view gets 'lost' and reloaded, the events are not showing the correct image.

**Comment by dgudim** [comment]
You basically want me to debug you code :)

**Comment by gusterfan2180** [comment]
Not necessarily.... if there is already a method for loading an event from Room that I am missing, I would want to use that. I'll take another look to make sure I am loading all events and then refreshing the calendar.

**Comment by kizitonwose** [comment]
@dgudim Thanks for helping out, your suggestions are spot-on. @gusterfan2180 I'll have to close this issue as it is an implementation problem. To answer the question in your last post, the library does not have an integration with Room. Please see the included examples and documentation for guidance.
