### ISSUE TITLE
Implement comparator interface for CalendarDay

### ISSUE THREAD

**Issue by ghost** [kizitonwose/Calendar#444]
### Feature
To add the CalendarDay object in a TreeSet, the Comparator interface implementation is required.
Please implement this interface on CalendarDay object, based on LocalDate comparison.

**Comment by kizitonwose** [comment]
Why not use the TreeSer constructor that allows you to provide a comparator:

```kotlin
val set = TreeSet<CalendarDay> { d1, d2 ->
    d1.date.compareTo(d2.date)
}
```

**Comment by kizitonwose** [comment]
Closing this as it is not necessary to implement it in the library.
