### ISSUE TITLE
HorizontalCalendar calendarScrollPaged broken after updating Compose version

### ISSUE THREAD

**Issue by ArturSechko** [kizitonwose/Calendar#445]
### Library information:
 - Version: 2.1.1
 - View or Compose module: compose

### Describe the bug**
`calendarScrollPaged` stops working after using latest compose versions. Almost every scroll event now counts as swipe and user is able to swipe through multiple pages with a single swipe.

### To Reproduce (if applicable)
Bump `androidx.compose.ui:ui` and `androidx.compose.foundation:foundation` versions to at least `1.4.0-alpha03` in sample app.

**Comment by kizitonwose** [comment]
Currently, alpha releases of compose [are not supported](https://github.com/kizitonwose/Calendar/blob/main/docs/Compose.md#compose-versions). I'll keep this issue open so I can revisit it when support for Compose 1.4 is added.

**Comment by kizitonwose** [comment]
The fix is available in the latest snapshot. This broke because the default snap behavior changed from single page in compose 1.3 to decayed snapping in 1.4.

**Comment by kizitonwose** [comment]
Released in [2.2.0](https://github.com/kizitonwose/Calendar/releases/tag/2.2.0)
