### ISSUE TITLE
Calendar 5 column (Monday - Friday) Only 

### ISSUE THREAD

**Issue by sevensanvour** [kizitonwose/Calendar#446]
Just want to ask if there's a way to set the calendar to 5 column and start from monday - friday only
and hide the data calendar for sunday and saturday

I'm new on this package.
and still working on creating the calendar with no sunday and saturday

### Library information:
 - Version: [e.g. 2.0.0]
 - View or Compose module: [e.g. View]

### Question:
[e.g. How do I do X or Y?]

**Comment by kizitonwose** [comment]
Hi, unfortunately, this is not supported in the library and there are no plans to add it in future versions.
