### ISSUE TITLE
Calendar 4 -> multiple set of selected dates

### ISSUE THREAD

**Issue by karagarwal** [kizitonwose/Calendar#447]
### Library information:
 - Version: [e.g. 2.1.1]
 - View

### Question:
Example 4 -> Continous Selection

How to  have multiple set of selector
for example, i want in a month 12 to 15 and 26 to 28 to be selected at the same time.
![Screenshot_2](https://user-images.githubusercontent.com/23401081/217883851-7e1b235c-8368-4897-8fe2-391431225111.png)

**Comment by kizitonwose** [comment]
You have to look at your binding logic. Example 4 is a good place to start. You will notice that we remove the current selection when a new selection is added. You need to adapt the logic for multiple range selections.
