### ISSUE TITLE
Changing row count dynamicaly in versions 2.x.x

### ISSUE THREAD

**Issue by Yennefer** [kizitonwose/Calendar#448]
Hi! First of all, thank you for the awesome library. I've been using it for a while in several of my projects.

Today I've been reading up on the migration guide to see if I can update my calendar to version 2.x.x. The only thing that made me rethink the whole migration process was the removing of `maxRowCount` property.
The problem is that, in my app, the user first sees the calendar in "Week mode" (maxRowCount = 1), but has the option to expand/collapse the view. To achieve this, I change `maxRowCount` from 1 to 6 and back.
If I understand correctly, in versions 2 and up I can only use two different calendar views and switch between them. But it would mean setting up and updating both views simultaneously and that solution isn't perfect, of course.

My question is - is there any other way to expand/collapse the calendar? What would be the best decision here?

**Comment by kizitonwose** [comment]
Hi, yes, you are right.  You have to manage both views. It is still possible to make the week view the default. Separating the views in v2 made a lot of other more beneficial use cases possible.
