### ISSUE TITLE
Snap behaviour for calendar with vertical orientation is broken

### ISSUE THREAD

**Issue by alincatalin** [kizitonwose/Calendar#451]
### Library information:
 - Version: 2.1.1
 - View or Compose module: View

### Describe the bug**
Scroll/Snap behaviour seems to be broken when using CalendarView - with both` app:cv_scrollPaged="true" ` and `app:cv_orientation="vertical"`. Every time I try to scroll to another month it either gets me back to where I started or it jumps back and forth.

### To Reproduce (if applicable)
The behaviour can be easily reproduced in the same (Example 2) - just change `app:cv_scrollPaged=` to `true` in the `example_2_fragment.xml`

**Comment by kizitonwose** [comment]
Released in [2.2.0](https://github.com/kizitonwose/Calendar/releases/tag/2.2.0)
