### ISSUE TITLE
Support other calenders than the gregorian

### ISSUE THREAD

**Issue by arijit4** [kizitonwose/Calendar#455]
### Feature
I want to implement a Bangla calender in my app. Bangla calender doesn’t match the dates on gregorian calender. So, it would be great if you could add suuport to add so.

### Tech (if applicable)
I've thought of a simple approach to this problem. The steps can be:
- get the `firstDayOfMonth` to map the day of week.
- get the number of days in current month to map the `inDates`
- get the number of days in last month to know the `outDates`
- get the number of days in next month to know the `inDates`

> Note: I will provide the informations (eg. `firstDayOfMonth`). I only need the UI to be implemented. 

Hope you understand and like my concept.

**Comment by kizitonwose** [comment]
Hey, thanks for the suggestion. Unfortunately, there are no plans to add/support more calendar types at the moment so I will have to close this. Sorry.

**Comment by arijit4** [comment]
Is there any way that I could use to implement this myself with your library?

**Comment by kizitonwose** [comment]
The data module is responsible for the month/date generation and [published separately](https://repo1.maven.org/maven2/com/kizitonwose/calendar/data/). You can pull the data module into your project, make the changes there and exclude the module in the calendar dependency.

Alternatively, you can just fork the library and make the required changes.
