### ISSUE TITLE
Monthly events lazy load ?

### ISSUE THREAD

**Issue by jscti** [kizitonwose/Calendar#456]
### Library information:
 - Version: latest
 - Compose module: From Example 3 "Horizontal Calendar"

### Question:
Is it possible to lazy load monthly events (for each day of the currently visible month) for the closest months ? Like in a ViewPager.
I see 2 loading patterns with your lib :
- load all events (like in your example 3) and pick the events you need depending on the currentVisibleMonth : previous/next transitions are OK but .... the events loading is not restricted to the current month (performance issue on large event database)
- load the monthly events when the currentVisibleMonth changes : but the previous/next transitions shows a FLASH of content because data of the next month has not been lazy loaded before the page shows up.

So Is there a way to lazy load efficiently month by month data ?
Thanks

**Comment by kizitonwose** [comment]
> load the monthly events when the currentVisibleMonth changes : but the previous/next transitions shows a FLASH of content because data of the next month has not been lazy loaded before the page shows up.

This is the way to go, but unless your connection is super fast, you won't always finish loading the adjacent month data before the user swipes to it. I'd suggest loading 2 or 3 months ahead to give the requests some time.
