### ISSUE TITLE
Can we using this library without installing desugar_jdk_libs?

### ISSUE THREAD

**Issue by vfa-trungnq** [kizitonwose/Calendar#457]
### Library information:
 - Version: [2.2.0]

### Question:
Actually I don't want to implement desugar_jdk_libs, is there anyway to remove desugar_jdk_libs?

**Comment by kizitonwose** [comment]
I have not tried but maybe you can try to remove the desugar dependencies using something like [this](https://stackoverflow.com/questions/21764128/how-do-i-exclude-all-instances-of-a-transitive-dependency-when-using-gradle)  and see if it works.

Alternatively, forking the project and removing desugar would also work.

**Comment by vfa-trungnq** [comment]
Thanks for your support.
