### ISSUE TITLE
Bug: monthCalendarView.findFirstVisibleDay()?.date & weekCalendarView.findFirstVisibleDay()?.date returns null after setup the calendar

### ISSUE THREAD

**Issue by jay22794** [kizitonwose/Calendar#458]
### Library information:
 - Version: [2.2.0]
 - View or compose module: [View]

### Describe the bug**
I am using Example 1 from the view module and encountered one bug. Once the setup method is called for the monthly and weekly calendars, when I try to get the first & last visible day using `monthCalendarView.findFirstVisibleDay()?.date` or `weekCalendarView.findFirstVisibleDay()?.date`, it always returns null.

### To Reproduce (if applicable)
1. Go to Example 1
2. Log the `monthCalendarView.findFirstVisibleDay()?.date`  or `weekCalendarView.findFirstVisibleDay()?.date` after the setup. It will be null. The same goes for the last date.

### Expected behavior (if applicable)
It should return the first/last date

Can you please look into it, and provide a fix or workaround? 

Thanks for the fantastic library!

**Comment by kizitonwose** [comment]
After the setup, the calendar still needs a layout pass to determine the first/last visible days. Did you try with 

```kotlin
calendarView.post { 
// find day here
}
```

**Comment by jay22794** [comment]
Yes, It worked. Thanks
