### ISSUE TITLE
Unresolved reference: rememberFirstMostVisibleMonth

### ISSUE THREAD

**Issue by Kimsoer** [kizitonwose/Calendar#460]
this line of code in example it show -> Unresolved reference: rememberFirstMostVisibleMonth
 val visibleMonth = rememberFirstMostVisibleMonth(state, viewportPercent = 90f)

**Comment by kizitonwose** [comment]
See [Utils.kt#L146](https://github.com/kizitonwose/Calendar/blob/992bf43b029cd3eceed938d9acd1ebd6ea3c4ed3/sample/src/main/java/com/kizitonwose/calendar/sample/compose/Utils.kt#L146), it is part of the sample project, not included in the library.
