### ISSUE TITLE
WeekCaledar RTL swiping problems

### ISSUE THREAD

**Issue by AttentiMobile** [kizitonwose/Calendar#466]
### Library information:
 - Version: 2.3.0
 - View or Compose module: View

### Describe the bug
WeekCalendarView RTL swiping problems: the current week return to staring week instead of moving to next/previous one.

### To Reproduce
Change the device to RTL language, like: Hebrew 
Open the first example, change to week mode, try to swipe the week day

This is working well in compose sample

**Comment by mohakapt** [comment]
I can confirm that the `CalendarPageSnapHelper` does not behave as expected in RTL layouts.
Even in LTR layouts, where it works, the scroll snapping feels a bit off. There is something different about it compared to the natural scroll snapping on (for example) a `ViewPager`.

**Comment by kizitonwose** [comment]
In version [2.2.0](https://github.com/kizitonwose/Calendar/releases/tag/2.2.0), I made major changes to the snap helper, can you see if your issue happens in version 2.1.0?

**Comment by aMittelmanMonkey** [comment]
i manage to overcome this issue by simply adding 

`android:layoutDirection="ltr"`

to the WeekCalendarView

**Comment by kizitonwose** [comment]
I reverted the `SnapHelper` in [2.4.1](https://github.com/kizitonwose/Calendar/releases/tag/2.4.1), this should fix this RTL issue and the issue mentioned by @mohakapt above.
