### ISSUE TITLE
Update Kotlin version

### ISSUE THREAD

**Issue by blakelee** [kizitonwose/Calendar#467]
### Library information:
 - Version: 2.3.0
 - View or Compose module: Compose

### Describe the bug**
There seems to be a change in the compose foundation API where SnapLayoutInfoProvider doesn't exist. It happens when I tried updating to Kotlin 1.8.20|21 and AGP 8.0.1

### To Reproduce (if applicable)
1. Create a calendar
2. Crash

### Expected behavior (if applicable)
It shouldn't crash

### Additional information
```
java.lang.NoSuchMethodError: No static method SnapLayoutInfoProvider(Landroidx/compose/foundation/lazy/LazyListState;Lkotlin/jvm/functions/Function3;)Landroidx/compose/foundation/gestures/snapping/SnapLayoutInfoProvider; in class Landroidx/compose/foundation/gestures/snapping/LazyListSnapLayoutInfoProviderKt; or its super classes (declaration of 'androidx.compose.foundation.gestures.snapping.LazyListSnapLayoutInfoProviderKt' appears in...
	at com.kizitonwose.calendar.compose.CalendarDefaults.pagedFlingBehavior(CalendarDefaults.kt:26)
	at com.kizitonwose.calendar.compose.CalendarDefaults.flingBehavior(CalendarDefaults.kt:37)
	at com.kizitonwose.calendar.compose.CalendarKt.Calendar(Calendar.kt:173)
	at com.kizitonwose.calendar.compose.CalendarKt.HorizontalCalendar(Calendar.kt:74)
```

**Comment by kizitonwose** [comment]
Are you using a [compatible](https://github.com/kizitonwose/Calendar/blob/main/docs/Compose.md#compose-versions) compose version?

**Comment by kizitonwose** [comment]
Please upgrade the calendar library to version 2.4.0-beta01, this has support for compose 1.5.0
