### ISSUE TITLE
Is there only kotlin version of this library

### ISSUE THREAD

**Issue by Shreyas25** [kizitonwose/Calendar#469]
Hello,

I am running the whole project as it is but I am facing issues.
Is there an only kotlin version of this ie without the compose modules?
How can I run only the sample app?
Also if there are any steps or document as to how to run this library will also help.

**Comment by kizitonwose** [comment]
Which issues are you facing?

**Comment by Shreyas25** [comment]
Could not resolve all files for configuration ':compose:detachedConfiguration9'.
Failed to transform FakeDependency.jar to match attributes {artifactType=_internal-d8-desugar-methods, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
Execution failed for D8BackportedMethodsGenerator: C:\Users\Asus\.gradle\android\FakeDependency.jar.

**Comment by kizitonwose** [comment]
Hey sorry for getting back now but this is an unfamiliar error. I am not sure if this has anything to do with the compose modules. To run the sample app, pull the repo locally, open the root project (not the sample project!) in Android Studio, then you can run the sample from inside Android Studio.

**Comment by kizitonwose** [comment]
I'll close this as it is not an issue with the library.
