### ISSUE TITLE
java.lang.NoSuchMethodError: No static method SnapLayoutInfoProvider

### ISSUE THREAD

**Issue by Ruineie** [kizitonwose/Calendar#472]
### Library information:
 - Version: [e.g. 2.3.0]
 - Compose 1.4.0 - beta2, 1.4.3 1.5.0 - alpha 03
 - Gradle 8.0.1

### Question:
[e.g. How do I do X or Y?]
I just simplely put the sample code of a horizontal calendar in the documents. It's built successfully, but crashed when launching. Here is the error. It seems something to do with the compose version. I've tried three versions of it. But the problem still exists. What am I doing wrong.
java.lang.NoSuchMethodError: No static method SnapLayoutInfoProvider(Landroidx/compose/foundation/lazy/LazyListState;Lkotlin/jvm/functions/Function3;)Landroidx/compose/foundation/gestures/snapping/SnapLayoutInfoProvider; in class Landroidx/compose/foundation/gestures/snapping/LazyListSnapLayoutInfoProviderKt; or its super classes (declaration of 'androidx.compose.foundation.gestures.snapping.LazyListSnapLayoutInfoProviderKt' appears in /data/app/~~DCl-quWJJyDjxp6OkZsMuQ==/com.cxxx.Playground-Xh6S20PJbwc0QCF4cIsAjw==/base.apk)

**Comment by Ruineie** [comment]
fixed. I used 
implementation 'androidx.compose.material3:material3-android:+', it turns out that I have to use a specific version.

**Comment by Ruineie** [comment]
new crash, when add
implementation 'com.google.accompanist:accompanist-permissions:0.31.3-beta'
into gradle, calender caused crash

**Comment by kizitonwose** [comment]
Please upgrade the calendar library to version 2.4.0-beta01, this has support for compose 1.5.0
