### ISSUE TITLE
Days background from other months peeking in currently showing month

### ISSUE THREAD

**Issue by wiryadev** [kizitonwose/Calendar#474]
### Library information:
 - Version: 1.1.0
 - View or Compose module:View

### Describe the bug**
Background View from next month showed up in current month. Let's say if we have colored background from May, then we change page to April, then in the side of April there will be some background "peeking". (screenshot attached).

### To Reproduce (if applicable)
This is my calendar day layout:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <View
        android:id="@+id/viewContinues"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/dimen_4dp"
        android:layout_marginBottom="@dimen/dimen_4dp" />

    <View
        android:id="@+id/viewRound"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="@dimen/dimen_4dp"
        android:layout_marginBottom="@dimen/dimen_4dp"/>

    <TextView
        android:id="@+id/tvCalendar"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:paddingHorizontal="@dimen/dimen_4dp"
        android:textSize="@dimen/text_size_14sp"
        tools:text="22" />

</FrameLayout>
```
And this is my CalendarView
```xml
<com.kizitonwose.calendarview.CalendarView
            android:id="@+id/calendarContainer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/dimen_12dp"
            app:cv_dayViewResource="@layout/layout_calendar_text"
            app:cv_orientation="horizontal"
            app:cv_scrollMode="paged" />
```

### Expected behavior (if applicable)
Background from other months not show up in current month.

### Screenshots? (if applicable)
| Next Month | Current Month |
|-------------|---------------|
|  ![](https://github.com/kizitonwose/Calendar/assets/26060382/a78c81af-37d4-4f2c-a6f1-6131b95d756a)  | ![](https://github.com/kizitonwose/Calendar/assets/26060382/4320bce8-e919-4023-971f-6686560426e7) |

### Additional information
This is not personal project therefore i can not share the full project nor i can update the version as i want. If more info is necessary i will try to make repro. Thanks

**Comment by kizitonwose** [comment]
> If more info is necessary i will try to make repro.

Yes, please do this. it will be much easier to look at the binding logic as I suspect it is the reason for this (views not recycled properly).

**Comment by wiryadev** [comment]
Hi, this is the repro link: https://github.com/wiryadev/CalendaRepro

![image](https://github.com/kizitonwose/Calendar/assets/26060382/b6b4e1c2-3641-4faa-9759-87e25283f362)
![image](https://github.com/kizitonwose/Calendar/assets/26060382/45415c1a-7861-4f66-8e3f-a47983053cfc)

**Comment by wiryadev** [comment]
Sorry for pinging, is there any info on this @kizitonwose ?

**Comment by kizitonwose** [comment]
Hey, I took a look today and everything looks ok in the sample, my guess is [this measuring logic](https://github.com/kizitonwose/Calendar/blob/93b46e0aeb7afc89074ad7cdf8662b08d9d7c740/library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt#L305) we had in 1.0.x versions, this has since been removed in 2.x.x releases. You mentioned in the initial post that updating the library is not an option for you so I am not sure how else to proceed.

**Comment by wiryadev** [comment]
> Hey, I took a look today and everything looks ok in the sample, my guess is [this measuring logic](https://github.com/kizitonwose/Calendar/blob/93b46e0aeb7afc89074ad7cdf8662b08d9d7c740/library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt#L305) we had in 1.x.x versions, this has since been removed in 2.x.x releases. You mentioned in the initial post that updating the library is not an option for you so I am not sure how else to proceed.

I see, thanks for explaining it
