### ISSUE TITLE
How can I access the day container view by position?

### ISSUE THREAD

**Issue by justin200914** [kizitonwose/Calendar#476]
### Feature
A clear and concise description of the feature.

### Tech (if applicable)
Add any other information that could help the development of this feature.

**Comment by kizitonwose** [comment]
The day is [set as the view tag](https://github.com/kizitonwose/Calendar/blob/b07684affef1cc8a6ea25d7fbe1dbc0a6f8fa25f/view/src/main/java/com/kizitonwose/calendar/view/internal/DayHolder.kt#L58) internally so you can use [findViewWithTag](https://developer.android.com/reference/android/view/View#findViewWithTag(java.lang.Object))
