### ISSUE TITLE
Issue with DayPosition

### ISSUE THREAD

**Issue by tkostov-topview** [kizitonwose/Calendar#477]
### Library information:
 - Version: 2.3.0
 - View

### Describe the bug**
Some dates are marked with **DayPosition.InDate / DatePosition.OutDate** instead of **DayPosition.MonthDate**

### To Reproduce
- Just have a calendar with several preloaded months
- Have a look at the red squares on the attached screenshot

### Expected behavior
- The In and Out dates to be properly calculated

### Screenshots?
<img width="356" alt="Screenshot 2023-06-22 at 10 16 09" src="https://github.com/kizitonwose/Calendar/assets/137383470/7d5264d1-4902-4034-a0f4-53fc6b6193ef">

### Additional information
Here's what I do based on the **DayPositon**
```
if (calendarDay.position == DayPosition.MonthDate) {
   // do some work 
} else {
  calendarDayView.visibility = View.INVISIBLE
}
```

**Comment by kizitonwose** [comment]
The views are reused, you must undo all changes:

```kotlin
if (calendarDay.position == DayPosition.MonthDate) {
  calendarDayView.visibility = View.VISIBLE // This is important
} else {
  calendarDayView.visibility = View.INVISIBLE
}
```
