### ISSUE TITLE
Add a y-axis as header look alike x axis header 

### ISSUE THREAD

**Issue by swatiomar27** [kizitonwose/Calendar#483]
I have a requirement to add support for y axis header like x axis header.

**Comment by kizitonwose** [comment]
Kindly add an example screenshot or some visual illustration to help me understand.

**Comment by swatiomar27** [comment]
<img width="1204" alt="Screenshot 2023-08-02 at 3 09 15 PM" src="https://github.com/kizitonwose/Calendar/assets/57611964/1342e2e4-cb73-4d00-a22b-a7de7e21305e">

Just like outlook calendar,
In the shared image, x- axis represents week and y-axis represents time. and x and y axis can be configurable.

**Comment by kizitonwose** [comment]
Unfortunately, this is outside the scope of the library. However, you can achieve something similar using the week-based calendar as a header and something else for the time. I'll close this issue.
