### ISSUE TITLE
Duplicate date when scrolling vertically

### ISSUE THREAD

**Issue by DanteAndroid** [kizitonwose/Calendar#492]
### Library information:
 - Version:  'com.kizitonwose.calendar:compose:2.3.0'

 - View or Compose module: compose

### Describe the bug
See the picture

### Expected behavior
No duplicate dates

### Screenshots? (if applicable)
<img width="342" alt="image" src="https://github.com/kizitonwose/Calendar/assets/10005563/e8667016-1ddb-4550-a4a0-516284f17d2d">

**Comment by kizitonwose** [comment]
Hey, can you reproduce this in the sample project? or kindly share a project where I can reproduce this.

**Comment by kizitonwose** [comment]
Closing this issue for now as there are no repro steps, please reopen it if you have more information.
