### ISSUE TITLE
Unresolved reference: displayText 

### ISSUE THREAD

**Issue by PRANAV62486** [kizitonwose/Calendar#493]
### Library information:
 - Version: [e.g. 2.0.0]
 - View or Compose module: [e.g. view]

### Describe the bug**
I was trying to implement Example5 of sample project and faced the issue "Unresolved reference: displayText". Basically displayText() method from YearMonth class is now not available. 

### To Reproduce (if applicable)
1. Go to 'Example5Fragment.kt'
2. Try to implement base class named "Example5Fragment" extending BaseFragment
4. now check the line no 104 of this file : "https://github.com/kizitonwose/Calendar/blob/main/sample/src/main/java/com/kizitonwose/calendar/sample/view/Example5Fragment.kt"
5. In this line displayText() method is not available "binding.exFiveMonthYearText.text = month.yearMonth.displayText()" 

### Expected behavior (if applicable)
It should be available 

### Screenshots? (if applicable)
![image](https://github.com/kizitonwose/Calendar/assets/63952401/2b9fcf62-244f-418d-8101-796a9e275467)

**Comment by kizitonwose** [comment]
This is an extenesion function in the sample:

```kotlin
fun YearMonth.displayText(short: Boolean = false): String {
    return "${this.month.displayText(short = short)} ${this.year}"
}
```
