### ISSUE TITLE
Unsupported class file major version 61 when running

### ISSUE THREAD

**Issue by DanteAndroid** [kizitonwose/Calendar#494]
### Library information:
 - Version:  'com.kizitonwose.calendar:compose:2.4.0-beta01'

### Describe the bug**
IDE got `Unsupported class file major version 61 ` when running project

**Comment by kizitonwose** [comment]
Hi, thanks for reporting this. Kindly let me know how to reproduce this as there is not much I can do with the limited information provided.

**Comment by CloudJoe** [comment]
jdk version mismatch, change Java_17 to your Java version

**Comment by CloudJoe** [comment]
jdk version mismatch, change Java_17 to your Java version

**Comment by CloudJoe** [comment]
> Hi, thanks for reporting this. Kindly let me know how to reproduce this as there is not much I can do with the limited information provided.

this issue can be closed now. jdk version mismatch, change Java_17 to your Java version

**Comment by DanteAndroid** [comment]
> > Hi, thanks for reporting this. Kindly let me know how to reproduce this as there is not much I can do with the limited information provided.
> 
> this issue can be closed now. jdk version mismatch, change Java_17 to your Java version

I got some issues when updated to jdk 17, so it would be nice if you could downgrade calendar to like jdk11

**Comment by DanteAndroid** [comment]
> Hi, thanks for reporting this. Kindly let me know how to reproduce this as there is not much I can do with the limited information provided.

Your project is built under jdk 17, thats why I got this problem. Please consider downgrade to support more jdk versions :)

**Comment by kizitonwose** [comment]
There are no plans to downgrade the jdk version in the library, unfortunately. Sorry for the inconvenience.

**Comment by DanteAndroid** [comment]
Any workaround for this issue? Thanks

**Comment by kizitonwose** [comment]
None that I know. But maybe some Googling might help.

**Comment by AhmadAyyaz1993** [comment]
> There are no plans to downgrade the jdk version in the library, unfortunately. Sorry for the inconvenience.

Hi @kizitonwose I am getting the same error in my project after upgrading the library to 2.x.x. Can you please provide us the proper resolution?

**Comment by kizitonwose** [comment]
@AhmadAyyaz1993 As I wrote [here](https://github.com/kizitonwose/Calendar/issues/500#issuecomment-1793670998), I cannot reproduce this jdk version mismatch issue using the sample project. If anyone in this thread would be kind enough to provide me with a working sample project where I can reproduce this issue, I would be happy to take a look.

However, the way I see it, sooner or later most projects will be on JDK 17, so I am not even sure I want to spend a lot of time on this issue (still very happy to take a look). If you have a version that currently works in your project then stick with it until the project is ready to migrate to JDK 17.

**Comment by kizitonwose** [comment]
Closing this for now as I still cannot reproduce it. As mentioned above, if someone is willing to prove a sample, I will take a look.
