### ISSUE TITLE
Is there a way to figure out position of the element?

### ISSUE THREAD

**Issue by akrulec** [kizitonwose/Calendar#495]
Hi, I'm using view's library, and I would to show continuity of something that is broken by the first and the last element of the week (and in the month view by the first or the last element of the month). For example:
- in week view, if the element is the first (left most), or the last (right most) hide something visually
- in the month view, (same as above) except for the "half weeks", i'd like the first day in the month, and the last day in the month to hide something visually.

Is that possible? If so, when and where can I set this up? I couldn't find any helper methods that would let me determine the position of the day in the recycler view. Thank you in advance.

Attaching screenshot. Each day individually knows whether to draw the line left of right of it, but the calendar should somehow also help it determine whether it's the last or first element in a row.
<img width="390" alt="Screenshot 2023-09-05 at 16 59 46" src="https://github.com/kizitonwose/Calendar/assets/94410932/4aa6db53-173f-483e-98d0-a24942151681">

**Comment by kizitonwose** [comment]
This is certainly possible with some work. You can store the month as suggested [here](https://github.com/kizitonwose/Calendar/issues/491#issuecomment-1700498703), then check the day position in the array when the day is bound. Alternatively, you can figure this out using the date itself but you'll need some more logic to get its position on the calendar grid.
