### ISSUE TITLE
view module,One month per page, vertical scrolling, adaptive height.

### ISSUE THREAD

**Issue by CloudJoe** [kizitonwose/Calendar#496]
### Library information:
 - Version: last
 - View

### Question:
One month per page, vertical scrolling, adaptive height.

**Comment by CloudJoe** [comment]
In View module,When I set the height to 'wrap_content,' orientation to 'vertical,' and scrollPaged to 'true,' the height occupies the entire page. I only want the height to fit exactly one month

**Comment by kizitonwose** [comment]
We have a similar setup in the `Example1Fragment` in the sample app and it works as expected

**Comment by CloudJoe** [comment]
> We have a similar setup in the `Example1Fragment` in the sample app and it works as expected

Thanks for your reply.
No,it's different,vertical orientation,it's height will fill the page,i just wanna show one month on view

**Comment by kizitonwose** [comment]
I was able to achieve this using `Example1Fragment` with a little bit of work. I have changed the calendar background color to show the content wrapping behavior:

Result:

https://github.com/kizitonwose/Calendar/assets/15170090/4f88a545-f65b-42c4-a85a-49c29d2520f6

XML:

```xml
    <com.kizitonwose.calendar.view.CalendarView
        android:id="@+id/exOneCalendar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/example_3_blue"
        app:cv_orientation="vertical"
        app:cv_daySize="square"
        app:cv_scrollPaged="true"
        app:cv_dayViewResource="@layout/example_1_calendar_day" />
```

Code:

```Kotlin
exOneCalendar.monthScrollListener = {
    val weekHeight = exOneCalendar.width / 7
    // If OutDateStyle is EndOfGrid, you could simply multiply weekHeight by 6.
    val visibleMonthHeight = weekHeight *
        exOneCalendar.findFirstVisibleMonth()?.weekDays.orEmpty().count()
    // Animate calendar height changes.
    val animator = ValueAnimator.ofInt(exOneCalendar.height, visibleMonthHeight)
    animator.addUpdateListener { anim ->
        exOneCalendar.updateLayoutParams {
            height = anim.animatedValue as Int
        }
        // A bug is causing the month calendar to not redraw its children
        // with the updated height during animation, this is a workaround.
        exOneCalendar.children.forEach { child ->
            child.requestLayout()
        }
    }
    animator.duration = 100
    animator.start()
}
```

**Comment by CloudJoe** [comment]
> I was able to achieve this using `Example1Fragment` with a little bit of work. I have changed the calendar background color to show the content wrapping behavior:
> 
> Result:
> 
>  rec.mp4 
> XML:
> 
> ```
>     <com.kizitonwose.calendar.view.CalendarView
>         android:id="@+id/exOneCalendar"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:background="@color/example_3_blue"
>         app:cv_orientation="vertical"
>         app:cv_daySize="square"
>         app:cv_scrollPaged="true"
>         app:cv_dayViewResource="@layout/example_1_calendar_day" />
> ```
> 
> Code:
> 
> ```kotlin
> exOneCalendar.monthScrollListener = {
>     val weekHeight = exOneCalendar.width / 7
>     // If OutDateStyle is EndOfGrid, you could simply multiply weekHeight by 6.
>     val visibleMonthHeight = weekHeight *
>         exOneCalendar.findFirstVisibleMonth()?.weekDays.orEmpty().count()
>     // Animate calendar height changes.
>     val animator = ValueAnimator.ofInt(exOneCalendar.height, visibleMonthHeight)
>     animator.addUpdateListener { anim ->
>         exOneCalendar.updateLayoutParams {
>             height = anim.animatedValue as Int
>         }
>         // A bug is causing the month calendar to not redraw its children
>         // with the updated height during animation, this is a workaround.
>         exOneCalendar.children.forEach { child ->
>             child.requestLayout()
>         }
>     }
>     animator.duration = 100
>     animator.start()
> }
> ```

Thank you very much for your patient assistance. in your demo, I successfully adapted height.Although there are still some issues in my app, at least your code is functional

**Comment by CloudJoe** [comment]
when I set calendarView's height to wrap_content in NestedScrollView, it doesn't work (crash)

**Comment by kizitonwose** [comment]
Could you please send me the XML to reproduce this using Example1Fragment?

**Comment by CloudJoe** [comment]
> Could you please send me the XML to reproduce this using Example1Fragment?

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/example_1_bg"
    android:clickable="true"
    android:focusable="true"
    android:orientation="vertical"
    tools:context=".view.Example1Fragment">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/exOneAppBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/example_1_bg_light"
        android:theme="@style/AppTheme.AppBarOverlay">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:padding="14dp">

            <TextView
                android:id="@+id/exOneYearText"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textColor="@color/example_1_white_light"
                android:textSize="24sp"
                tools:text="2019" />

            <TextView
                android:id="@+id/exOneMonthText"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:singleLine="true"
                android:fontFamily="sans-serif-light"
                android:textColor="@color/example_1_white"
                android:textSize="32sp"
                android:ellipsize="marquee"
                tools:text="April" />

        </LinearLayout>

        <include
            android:id="@+id/legendLayout"
            layout="@layout/calendar_day_legend_container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:layout_marginBottom="10dp" />

    </com.google.android.material.appbar.AppBarLayout>
<androidx.core.widget.NestedScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.kizitonwose.calendar.view.CalendarView
            android:id="@+id/exOneCalendar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:cv_orientation="vertical"
            app:cv_daySize="square"
            app:cv_scrollPaged="true"
            app:cv_dayViewResource="@layout/example_1_calendar_day" />

        <com.kizitonwose.calendar.view.WeekCalendarView
            android:id="@+id/exOneWeekCalendar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:cv_dayViewResource="@layout/example_1_calendar_day" />

        <CheckBox
            android:id="@+id/weekModeCheckBox"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|center_horizontal"
            android:layout_marginBottom="20dp"
            android:buttonTint="@color/example_1_white"
            android:padding="2dp"
            android:text="@string/week_mode"
            android:textColor="@color/example_1_white"
            android:textSize="18sp" />

    </FrameLayout>

</androidx.core.widget.NestedScrollView>
</LinearLayout>

 it didn't crash in fragment1,but App lag when navigate to fragment1,and crash in my app

**Comment by CloudJoe** [comment]
I guess,Because the RecyclerView has a 'wrap_content' height and is wrapped inside a NestedScrollView, it leads to an unlimited increase in its height during the initial load, resulting in an OutOfMemoryError. It doesn't crash immediately.
![企业微信截图_16944833239430](https://github.com/kizitonwose/Calendar/assets/25249779/0548690c-32c7-4e74-9c71-8541b2a3a957)
![企业微信截图_16944833782828](https://github.com/kizitonwose/Calendar/assets/25249779/ddf14d94-206f-4e10-b10b-a7bc903a5991)

**Comment by CloudJoe** [comment]
I guess,Because the RecyclerView has a 'wrap_content' height and is wrapped inside a NestedScrollView, it leads to an unlimited increase in its height during the initial load, resulting in an OutOfMemoryError. It doesn't crash immediately.
![企业微信截图_16944833239430](https://github.com/kizitonwose/Calendar/assets/25249779/0548690c-32c7-4e74-9c71-8541b2a3a957)
![企业微信截图_16944833782828](https://github.com/kizitonwose/Calendar/assets/25249779/ddf14d94-206f-4e10-b10b-a7bc903a5991)

**Comment by CloudJoe** [comment]
Perhaps your demo has a relatively small memory footprint,so it didn't crash

**Comment by kizitonwose** [comment]
Does this also happen if you set a fixed height on the CalendarView in XML?

**Comment by CloudJoe** [comment]
> Reference in
yes,fixed height is ok

**Comment by kizitonwose** [comment]
As the height will be calculated dynamically using the logic discussed [here](https://github.com/kizitonwose/Calendar/issues/496#issuecomment-1713482551), maybe it is okay to use a fixed height in XML?

**Comment by CloudJoe** [comment]
> As the height will be calculated dynamically using the logic discussed [here](https://github.com/kizitonwose/Calendar/issues/496#issuecomment-1713482551), maybe it is okay to use a fixed height in XML?

ok,thanks : )
