### ISSUE TITLE
How can I add my logic to the month change event

### ISSUE THREAD

**Issue by dadyarri** [kizitonwose/Calendar#498]
### Library information:
 - Version: 2.4.0-beta01
 - View or Compose module: Compose

### Question:
I want to pull information from server about events in one exact month during (of after) changing month. Progrmatically I can do that in button click handlers, but this doesn't work with swipes. I'm using Horizontal month calendar

**Comment by kizitonwose** [comment]
See [this](https://github.com/kizitonwose/Calendar/blob/369a5681b606eda486b05cacbb41746df6211cea/sample/src/main/java/com/kizitonwose/calendar/sample/compose/Utils.kt#L96) or [this](https://github.com/kizitonwose/Calendar/blob/369a5681b606eda486b05cacbb41746df6211cea/sample/src/main/java/com/kizitonwose/calendar/sample/compose/Utils.kt#L115) in the sample app.

**Comment by dadyarri** [comment]
Thanks. Made it work, but with little delay (events updated after month change), but it think it's not a big deal
