### ISSUE TITLE
Some calendar month days do not appear when I scroll the calendar vertically

### ISSUE THREAD

**Issue by anmolgupta22** [kizitonwose/Calendar#502]
### Library information:
 - Version: [ 2.1.1]
 - View or Compose module: [view]

### Describe the bug**
i have add already exists google calendar Events in the calendar then after i scroll the calendar so some calendar month days do not appear when I scroll the calendar vertically

### To Reproduce (if applicable)
1. Go to 'scroll the calendar then back to the previous calendar month'

### Screenshots? (if applicable)
If applicable, add screenshots or screen recordings to help explain the problem.
![MicrosoftTeams-image](https://github.com/kizitonwose/Calendar/assets/92536916/4dfcbcc9-f2e4-4f0c-9eda-903635585d09)

### Additional information
Add any other information about the bug here.

**Comment by kizitonwose** [comment]
If you hid some days in your binding logic you also have to unhide them otherwise they remain hidden. Can you see if this issue happens in the sample project?

**Comment by kizitonwose** [comment]
I will close this issue, please reopen it if this is really a library issue.
