### ISSUE TITLE
collapse the monthly view into a weekly view

### ISSUE THREAD

**Issue by JoeVX** [kizitonwose/Calendar#503]
### Library information:
 - Version: [2.4.0]
 - View 

### Question:
Is there a way to collapse the monthly view into a weekly view with a single row height, and have that row display the current week containing the current day?

**Comment by CloudJoe** [comment]
What I mean is to achieve this using the same view,because I have bound a lot of data to this view, if I switch to a new weekly view, the data will need to be rebound.

**Comment by kizitonwose** [comment]
This is exactly what is done in the first example in the sample project, please take a look at the code: [Example1Fragment.kt](https://github.com/kizitonwose/Calendar/blob/main/sample/src/main/java/com/kizitonwose/calendar/sample/view/Example1Fragment.kt)

<img src="https://user-images.githubusercontent.com/15170090/195636303-a99312c9-23a3-44cd-8a38-6ba21b3c4802.gif" width="300">

**Comment by kizitonwose** [comment]
> What I mean is to achieve this using the same view,because I have bound a lot of data to this view, if I switch to a new weekly view, the data will need to be rebound.

I see that you do not want to use the week view provided in the library as shown in the examples. Unfortunately, the month calendar view cannot be collapsed into a week view. Note that with minimal effort, the core binding logic can be extracted and reused for the month and week views so rebinding data should not be an issue.

**Comment by kizitonwose** [comment]
I guess I can close this issue as it is not supported in the library, feel free to reopen it if you need more help.
