### ISSUE TITLE
java.lang.IllegalArgumentException: The initial value must have an associated anchor.

### ISSUE THREAD

**Issue by ParkJongJoon7128** [kizitonwose/Calendar#504]
### Library information:
```
compose_version = '1.4.7'
id 'org.jetbrains.kotlin.android' version '1.8.21' apply false

def new_calendar = "2.0.3"
implementation "com.kizitonwose.calendar:compose:$new_calendar"
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
```

### Question:
When i sync this library and use this calendar(HorizontalCalendar, WeekCalendar), there is error.
Specifically, after syncing this library to my project, the view structure of the screen with the calendar has changed. In particular, the location of the FAB has changed, and errors occur when you click FAB to perform any function, or when an event occurs by clicking day.

Even if I search for this error by Googling, the only related symptoms are BottomSheet contents, so I register issue.

![image](https://github.com/kizitonwose/Calendar/assets/51289286/0573647d-b97a-4e98-8d0e-da0da40dc78c)

**error**
`java.lang.IllegalArgumentException: The initial value must have an associated anchor.`

**Comment by kizitonwose** [comment]
Hi, can you please add some repro steps?

**Comment by ParkJongJoon7128** [comment]
here is my project repo
[https://github.com/Pond-Lotus/lotus_aos](url)

and this is the recording when i run this app 
[untitled.zip](https://github.com/kizitonwose/Calendar/files/13257111/untitled.zip)

-------------------------------------------------------------------------------------------------

actually when i changed the previous other library to this library, the corresponding screen design structure is totally changed, twisted. So, i'm very confused now.

**Comment by kizitonwose** [comment]
Hi, the provided sample requires login and is in a language I do not understand.

<img src="https://github.com/kizitonwose/Calendar/assets/15170090/dacca45e-bc68-4170-833b-b1d7c2880aae" width="300">

**Comment by ParkJongJoon7128** [comment]
oh its login screen.
The first input is for 'id' and second input is for 'password'

I'll give you my account
id: **whdwnsdk8111@naver.com**
pw: **whdwnsdk2!**

**Comment by kizitonwose** [comment]
Clicking the button does nothing

https://github.com/kizitonwose/Calendar/assets/15170090/7b9ec5d2-ad3b-49ee-ade2-d4913187270f

**Comment by kizitonwose** [comment]
I have removed all the calendar code from the project but it is still crashing with the same error so I think the issue is not from the library. 

https://github.com/kizitonwose/Calendar/assets/15170090/d690deed-5238-4b03-8224-5ff17869436e

**Comment by ParkJongJoon7128** [comment]
No, since I used this library, the view structure of the calendar screen has been completely distorted, and there has been an issue.

The particular point is the FAB position. After adding this library, the FAB, which should be in its original position, has been slammed down the screen and is out of range of the screen. This is the biggest issue.

Secondly, BottomSheet's Sheet ContentHeight is not applicable. I originally declared 0.dp as the default and used it, but after adding this library, the value for 0.dp became unavailable.

**Comment by kizitonwose** [comment]
I do not think I can help with this, unfortunately.
