### ISSUE TITLE
Fast Scrolling

### ISSUE THREAD

**Issue by MostafaKader56** [kizitonwose/Calendar#505]
### Library information:
 - Version: 2.4.0
 - View module.

### Describe the bug**
When the scroll bar is pulled quickly, the scroll movement is not smoothly and some problems occur, as the days are repeated and/or the days not be in the correct position.

**Comment by MostafaKader56** [comment]
the device i debugging on it is: Samsung SM-A515F
i write the same code as the documentation [here](https://github.com/kizitonwose/Calendar/blob/main/docs/View.md)

**Comment by kizitonwose** [comment]
Hi, I have tested on this exact device with the sample project (view module sample) and cannot reproduce this issue. Can you check if this is happening in the sample app on your end? I assume this could be an issue in your project.

<img src="https://github.com/kizitonwose/Calendar/assets/15170090/162c2c4a-2c47-4b1b-aa3c-3e1adf936b27" width="300">
