### ISSUE TITLE
Stable calendar height during scroll

### ISSUE THREAD

**Issue by trupizzza** [kizitonwose/Calendar#506]
### Library information:
 - Version: 2.4.0
 - View or Compose module: View

### Question:
How to show constant 5x7 calendar grid?
With any app:cv_outDateStyle, calendar shows 6 rows at some point, even if the last row consists of out days only.
I want to see whole current month, with empty "gaps" filled equally with in and out dates

### "Bad" behavior

Example 1 (6 rows instead of 5):

![image](https://github.com/kizitonwose/Calendar/assets/16307140/bd2f8b62-2b9f-4ff7-9599-fd62f2e8d362)

Example 2 (last row consists fully of outdates):

![image](https://github.com/kizitonwose/Calendar/assets/16307140/07535480-9fb6-4ffa-a90f-3a0417b2b5d9)

### What I want to achieve:

![image](https://github.com/kizitonwose/Calendar/assets/16307140/84f6eeaf-8645-4178-9247-ca72cc2fcc3c)

Any help would be appreciated

**Comment by kizitonwose** [comment]
> I want to see whole current month, with empty "gaps" filled equally with in and out dates

This is not how a calendar works. If you do not want to fill the empty row, you can use `outDateStyle` = `endOfRow`, but there is no way to make a calendar to show the same number of days for in and out dates for every month.

**Comment by trupizzza** [comment]
> > I want to see whole current month, with empty "gaps" filled equally with in and out dates
> 
> This is not how a calendar works. If you do not want to fill the empty row, you can use `outDateStyle` = `endOfRow`, but there is no way to make a calendar to show the same number of days for in and out dates for every month.

First of all, thanks for fast reply!

It is ok for me to have different amount of in and out dates, the main goal is to have each month of calendar layed out in 5 rows, not 6

Can I achieve that type of behavior?

**Comment by kizitonwose** [comment]
> First of all, thanks for fast reply!
>
> It is ok for me to have different amount of in and out dates, the main goal is to have each month of calendar layed out in 5 rows, not 6 


That's not possible with the library. Each month can have either a dynamic number of rows or fixed (6 x 7 grid)

**Comment by trupizzza** [comment]
Thanks!

**Comment by gohanSaki114** [comment]
How did you remove the month name at the end of the current month ? did you do something with the outDateStyle?
