### ISSUE TITLE
FirstDayOfMonth with out and in dates

### ISSUE THREAD

**Issue by mak1nt0sh** [kizitonwose/Calendar#508]
Is it possible to set first day of month for compose? Also retaining the In and Out days? To achieve calendar like this:

![Screenshot_20231111-192155](https://github.com/kizitonwose/Calendar/assets/33786477/f5e081d2-5e02-4f81-a937-ff54efe875fa)

**Comment by kizitonwose** [comment]
```kotlin
    val state = rememberCalendarState(
        startMonth = startMonth,
        endMonth = endMonth,
        firstVisibleMonth = currentMonth,
        firstDayOfWeek = firstDayOfWeek,
		outDateStyle = EndOfGrid, // This is what you need
    )
```

**Comment by mak1nt0sh** [comment]
But how do I set 15 day as the first of the month? I can only set the day of week. Like in image example.

**Comment by kizitonwose** [comment]
Calendars do not work like that. You can't force a day to be the first in every month.

**Comment by mak1nt0sh** [comment]
There are use cases for financial periods. It's not a first day of month but more like a displayed date range from middle of the month to next one.

Say i.e. you get your salary on 15th and want to plot a calendar of expenses till the next salary.

**Comment by kizitonwose** [comment]
I get you now, you want to remove all the days before a certain date on the calendar. That is currently not possible.
