### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by bmc08gt** [kizitonwose/Calendar#510]
### Feature
Are you open to a PR to make this work with Kotlin Multiplatform? I am in the process of making it compatible for a project I am working on and would love to push it upstream.

### Tech (if applicable)
Add any other information that could help the development of this feature.

**Comment by kizitonwose** [comment]
Hi, yes, that would be very much appreciated. Thank you!

**Comment by Jimaloo** [comment]
Hi @bmc08gt  , how is this going?

**Comment by bmc08gt** [comment]
> Hi @bmc08gt  , how is this going?

Hit some unexpected issues outside of this migration. Hopeful to get the PR up this week or next.

**Comment by bmc08gt** [comment]
> > Hi @bmc08gt  , how is this going?
> 
> Hit some unexpected issues outside of this migration. Hopeful to get the PR up this week or next.

Just an update. Have core library updated. Just going through sample to make it happy now. :)

**Comment by BikramDroid** [comment]
> > > Hi @bmc08gt  , how is this going?
> > 
> > 
> > Hit some unexpected issues outside of this migration. Hopeful to get the PR up this week or next.
> 
> Just an update. Have core library updated. Just going through sample to make it happy now. :)

Thanks for the support, when do you think this would be available?

**Comment by alaegin** [comment]
Hi! How is it going?

**Comment by WojciechOsak** [comment]
Hi @bmc08gt , any updates ? :)

**Comment by Murzify** [comment]
Hi @bmc08gt ! How is it going?

**Comment by ryanw-mobile** [comment]
Not sure if it turned out to be impossible to make it KMP compatible, but since the compose part, as mentioned, is backed by LazyColumn/LazyRow for compose, I hope the existing Compose Multiplatform is sufficient enough to make it run on all platforms (not just Android/iOS) if this task can eventually move forward?

**Comment by kizitonwose** [comment]
After much thought, I have decided to take on the multiplatform task. I started a discussion [here](https://github.com/kizitonwose/Calendar/discussions/554) on how I intend to approach this, I will lock this thread as there has not been much activity besides the update requests. 

Huge thanks to @bmc08gt for the initial offer and effort to bring this library to multiplatform users.

**Comment by kizitonwose** [comment]
Released in [2.6.0-alpha03](https://github.com/kizitonwose/Calendar/releases/tag/2.6.0-alpha03)
