### ISSUE TITLE
Horizontal Calendar crashing

### ISSUE THREAD

**Issue by shahrukhahmed94** [kizitonwose/Calendar#512]
### Library information:
 - Version: [e.g. 2.3.0]
 - View or Compose module: [e.g. Compose]

### Describe the bug**
java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~lw_C9tmkwEYFPHPnXhGcwQ==/com.avanza.ourpol-teQbiLIwCZ74LhsbzJiBmw==/base.apk)
                                                                                                    

### To Reproduce (if applicable)
1. Go to '....'
4. See '....'

### Screenshots? (if applicable)
If applicable, add screenshots or screen recordings to help explain the problem.

### Additional information
Add any other information about the bug here.

**Comment by kizitonwose** [comment]
Please verify that you are using the appropriate calendar version.

<img width="307" alt="Screenshot" src="https://github.com/kizitonwose/Calendar/assets/15170090/93d0a1eb-0a7d-48a8-9c33-b2111215ca69">

**Comment by Shahrukh12345** [comment]
My compose version is 1.5.2 & Calendar lib version is 2.3.0 where as if I try to compile to 2.4 then my app stops compiling

**Comment by kizitonwose** [comment]
Sorry but I am unable to reproduce this, kindly include a minimal sample project. If you can reproduce it with the included sample project, that would be great.

**Comment by Ezioer** [comment]
> My compose version is 1.5.2 & Calendar lib version is 2.3.0 where as if I try to compile to 2.4 then my app stops compiling getting this error (/com/kizitonwose/calendar/core/CalendarDay.class) class file has wrong version 61.0, should be 55.0 Please remove or make sure it appears in the correct subdirectory of the classpath.↳

I had the same problem, have you solved it yet?
