### ISSUE TITLE
Yearly calendar view

### ISSUE THREAD

**Issue by nAkhmedov** [kizitonwose/Calendar#513]
### Feature
Any tricks to display yearly view by using this library? Thanks in advance!

![telegram-cloud-photo-size-5-6311896965293652696-y](https://github.com/kizitonwose/Calendar/assets/8067423/0905932f-bb26-4350-876d-bd999fd75cca)

**Comment by kizitonwose** [comment]
I was able to get something basic by using `LazyVerticalGrid` internally. But I have now realized this would need more work than I initially thought. I am wondering if there is enough use case to justify the effort required to bake this into the library or if you are better off forking the library and making the required changes.

<img src="https://github.com/kizitonwose/Calendar/assets/15170090/9088e2ba-1a55-4b22-a1bf-32884f84c7e9" width="300">
