### ISSUE TITLE
Displaying Calendar for Weekdays Only

### ISSUE THREAD

**Issue by V41ER** [kizitonwose/Calendar#515]
### Feature
Hello Kizitonwose Calendar Team,

I hope this message finds you well. I am currently integrating your calendar library into my Android application and would like to customize the calendar to display only weekdays, excluding weekends.

![Screenshot_20231211_143600_fr trecobat brick](https://github.com/kizitonwose/Calendar/assets/135588007/14620df7-4d31-477c-b744-a8c305437ae3)

I have explored various options, but I am encountering challenges in achieving this specific configuration. My goal is to have a calendar that shows weekdays (Monday to Friday) and omits the weekends, allowing for larger day sizes.

Could you please provide guidance or suggestions on how to achieve this customization within the Kizitonwose Calendar library?

Your assistance is highly appreciated.

Thank you,
Francis

**Comment by kizitonwose** [comment]
Are you using the compose library or view?

**Comment by kizitonwose** [comment]
Unfortunately, this is not possible at the moment and I do not think it is worth adding to the core library as the use case is too specific. However, you can fork the library and add these changes for personal use. I tried to see if I could add it but found myself rewriting more things than I wanted.

Here's what it looks like just by changing [this](https://github.com/kizitonwose/Calendar/blob/f58f53b520e21d52dab076a0053bebecdee4294a/view/src/main/java/com/kizitonwose/calendar/view/internal/WeekHolder.kt#L55) and [this](https://github.com/kizitonwose/Calendar/blob/f58f53b520e21d52dab076a0053bebecdee4294a/view/src/main/java/com/kizitonwose/calendar/view/internal/WeekHolder.kt#L56) from `dayHolders.count()` to 5 and setting the views with Saturday and Sunday to `View.GONE` (of course you would need to update the weekday header too):

<img src="https://github.com/kizitonwose/Calendar/assets/15170090/d62f7185-ddda-4e8e-bcc1-39bbae55a921" width="300">

**Comment by kizitonwose** [comment]
Closing this as there is no plan to implement it in the library

**Comment by V41ER** [comment]
Hey ! I tested your solution look at my code it doesn't really work from my fork :
If I take Example2Fragment :
```
calendarView.dayBinder = object : MonthDayBinder<DayViewContainer> {
            override fun create(view: View) = DayViewContainer(view)

            override fun bind(container: DayViewContainer, data: CalendarDay) {
                container.day = data
                val textView = container.textView

                if (isWeekend(data.date)) {
                    // Masquer la vue du jour si c'est un week-end
                    textView.makeInVisible()
                } else {
                    textView.makeVisible()
                    textView.text = data.date.dayOfMonth.toString()

                    if (data.position == DayPosition.MonthDate) {
                        when (data.date) {
                            selectedDate -> {
                                textView.setTextColorRes(R.color.example_2_white)
                                textView.setBackgroundResource(R.drawable.example_2_selected_bg)
                            }
                            today -> {
                                textView.setTextColorRes(R.color.example_2_red)
                                textView.background = null
                            }
                            else -> {
                                textView.setTextColorRes(R.color.example_2_black)
                                textView.background = null
                            }
                        }
                    } else {
                        textView.makeInVisible()
                    }
                }
            }

            // Fonction pour vérifier si une date est un jour de week-end
            private fun isWeekend(date: LocalDate): Boolean {
                val dayOfWeek = date.dayOfWeek
                return dayOfWeek == DayOfWeek.SATURDAY || dayOfWeek == DayOfWeek.SUNDAY
            }
        }
 ```
 
 This modification allows me to hide weekends.
 
 and I've also modified the WeekHolder code:
 ```
     fun inflateWeekView(parent: LinearLayout): View {
        return WidthDivisorLinearLayout(parent.context).apply {
            weekContainer = this
            val width = if (daySize.parentDecidesWidth) MATCH_PARENT else WRAP_CONTENT
            val height = if (daySize.parentDecidesHeight) MATCH_PARENT else WRAP_CONTENT
            val weight = if (daySize.parentDecidesHeight) 1f else 0f
            layoutParams = LinearLayout.LayoutParams(width, height, weight)
            orientation = LinearLayout.HORIZONTAL
            weightSum = 5.toFloat()
            widthDivisorForHeight = if (daySize == DaySize.Square) 5 else 0
            for (holder in dayHolders) {
                addView(holder.inflateDayView(this))
            }
        }
    }
 ```
 
 But with these changes I've got an empty page!

**Comment by kizitonwose** [comment]
```kotlin
 widthDivisorForHeight = if (daySize == DaySize.Square) 5 else 0
   for (holder in dayHolders) { // This is a loop of 7 items, you need to add 5 items
       addView(holder.inflateDayView(this))
   }
```

**Comment by V41ER** [comment]
file:///home/francois/T%C3%A9l%C3%A9chargements/Screenshot_20231219-133556_Calendar%20Sample.jpg

**Comment by V41ER** [comment]
![Screenshot_20231219-133556_Calendar Sample](https://github.com/kizitonwose/Calendar/assets/135588007/fa1fa345-0b28-4627-a472-dab43ffba0c3)

It was the same problem look the screenshot

**Comment by V41ER** [comment]
And I did modify the code though :
```
    fun inflateWeekView(parent: LinearLayout): View {
        return WidthDivisorLinearLayout(parent.context).apply {
            weekContainer = this
            val width = if (daySize.parentDecidesWidth) MATCH_PARENT else WRAP_CONTENT
            val height = if (daySize.parentDecidesHeight) MATCH_PARENT else WRAP_CONTENT
            val weight = if (daySize.parentDecidesHeight) 1f else 0f
            layoutParams = LinearLayout.LayoutParams(width, height, weight)
            orientation = LinearLayout.HORIZONTAL
            weightSum = 5.toFloat()
            widthDivisorForHeight = if (daySize == DaySize.Square) 5 else 0
            for (holder in dayHolders) { // This is a loop of 7 items, you need to add 5 items
                addView(holder.inflateDayView(this))
            }
        }
    }
```

**Comment by V41ER** [comment]
Le pire c'est quand je met le code comme ceci j'ai un résultat sur 4 qui est vraiment bien ! mais pour 5 impossible ... :

**Comment by V41ER** [comment]
The worst thing is when I put the code like this I get one result out of 4 which is really good! but for 5 impossible ...

```
    fun inflateWeekView(parent: LinearLayout): View {
        return WidthDivisorLinearLayout(parent.context).apply {
            weekContainer = this
            val width = if (daySize.parentDecidesWidth) MATCH_PARENT else WRAP_CONTENT
            val height = if (daySize.parentDecidesHeight) MATCH_PARENT else WRAP_CONTENT
            val weight = if (daySize.parentDecidesHeight) 1f else 0f
            layoutParams = LinearLayout.LayoutParams(width, height, weight)
            orientation = LinearLayout.HORIZONTAL
            weightSum = 8.toFloat()
            widthDivisorForHeight = if (daySize == DaySize.Square) 4 else 0
            for (holder in dayHolders) {
                addView(holder.inflateDayView(this))
            }
        }
    }
```

![Screenshot_20231219-143844_Calendar Sample](https://github.com/kizitonwose/Calendar/assets/135588007/9ed5a5c4-c513-4e01-87cd-4d711889b270)
