### ISSUE TITLE
Need help to show 5 day of week equally divided in UI

### ISSUE THREAD

**Issue by min-naing** [kizitonwose/Calendar#523]
### Library information:
 - Version: 2.4.1
 - View or Compose module: Compose

### Question:
I would like to show 5 day of week not 7.
How do I fix day is not equally divided in month body view?
![Screenshot_20240111_111508](https://github.com/kizitonwose/Calendar/assets/25186412/6e5e29a9-2081-4322-bc17-4306d99912a3)

**Comment by kizitonwose** [comment]
I'm sorry this feature is not supported in the library.
