### ISSUE TITLE
How to disable previous swipe functionality in calendar view when showing current month.

### ISSUE THREAD

**Issue by teamswork** [kizitonwose/Calendar#529]
Here i have attached screen shot for your reference.  I need to disable previous swipe functionality when only calendar showing current month. I don't want to show past month to user when it showing current month. 
![Screenshot_2024-02-01-17-11-27-72_9b71651e86049036254f432922cb845d (1)](https://github.com/kizitonwose/Calendar/assets/77773445/09f12af8-7efe-40aa-974a-ac69c04d3658)

**Comment by kizitonwose** [comment]
Set a scroll listener on the calendar, inside the callback you check if the month is the current month `YearMonth.now()`, then hide the left arrow. Also setup your calendar with `YearMonth.now()` as the `startDate` so it cannot scroll beyond that.
