### ISSUE TITLE
Range Date Picker selector in WeekCalendar

### ISSUE THREAD

**Issue by annng** [kizitonwose/Calendar#534]
### Feature
<img width="345" alt="image" src="https://github.com/kizitonwose/Calendar/assets/31025016/62a1d732-a704-4953-ab09-b4c83e792275">

Can we create this weekCalendar to be range date selection?

### Tech (if applicable)
I try to copy binder on range date selection on Example4Fragment, but I got some issue it has different data type on their binder

**Comment by AlDm180990** [comment]
# - []()3
