### ISSUE TITLE
Add Grid Calendar

### ISSUE THREAD

**Issue by acolombo11** [kizitonwose/Calendar#535]
### Feature
Add Grid calendar implementation as part of the library

### Tech (if applicable)
Now there are HorizontalCalendar and VerticalCalendar, using LazyRow and LazyColumn, containg CalendarMonths elements.
It would be cool to have HorizontalGridCalendar and VerticalGridCalendar, using LazyHorizontalGrid and lazyVerticalGrid, to use in bigger UIs such as tablets or tvs.

**Comment by buinsoft** [comment]
Hi there, is there any solution to this issue?

**Comment by 11610197109** [comment]
Hi there, is there any solution to this issue?

**Comment by kizitonwose** [comment]
Working on this, but would be ready in about 2 or 3 months, considering that I am also working on finalizing the multiplatform project which is currently in alpha. 

**I'll keep this issue open for discussion, but please refrain from posting comments solely asking about the release date, as such comments do not add any value.**

<img src="https://github.com/user-attachments/assets/0d5f1125-edf8-419a-a29d-2e81de33d0bf" width="500">

<img src="https://github.com/user-attachments/assets/3d219484-cd1d-48cf-ba39-25c14075cb21" width="500">

**Comment by kizitonwose** [comment]
Now available in [2.5.3](https://github.com/kizitonwose/Calendar/releases/tag/2.5.3) for compose version 1.6.x  and [2.6.0-beta03 [A] | 2.6.0-alpha04 [MP]](https://github.com/kizitonwose/Calendar/releases/tag/2.6.0-beta03-A%7C2.6.0-alpha04-MP) for compose version 1.7.x. 

See [documentation](https://github.com/kizitonwose/Calendar/blob/main/docs/Compose.md#year-calendar).
