### ISSUE TITLE
Home Sample Sample Inquiry 

### ISSUE THREAD

**Issue by a1031737** [kizitonwose/Calendar#537]
Sorry, I want to ask about a sample of the homepage. As shown below, can you tell me where I can find a similar sample, or which file in share it is? 
![Screenshot_2024-03-28-00-44-00-063_com android chrome](https://github.com/kizitonwose/Calendar/assets/58047638/3ce535ce-d7b5-4c0e-be93-d894caaf3272)

**Comment by kizitonwose** [comment]
[Example3Fragment.kt](https://github.com/kizitonwose/Calendar/blob/main/sample/src/main/java/com/kizitonwose/calendar/sample/view/Example3Fragment.kt)
