### ISSUE TITLE
from example1 to exapmle8,i can't find this example

### ISSUE THREAD

**Issue by jeff-sun** [kizitonwose/Calendar#543]
### Library information:
 - Version: [2.5.1]
 - View or Compose module: [View]

### Question:
[from example1 to exapmle8,i can't find this example]
![image](https://github.com/kizitonwose/Calendar/assets/20920804/9cfa792f-0743-4012-8562-36583e52b342)

**Comment by kizitonwose** [comment]
This is not available in the view module. But you can wrap the composable in a [ComposeView](https://developer.android.com/reference/kotlin/androidx/compose/ui/platform/ComposeView) and use it like any other view.
