### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yuanmaio** [kizitonwose/Calendar#544]
### Library information:
 - Version: [e.g. 2.0.0]
 - View or Compose module: [e.g. View]

### Question:
[e.g. How do I do X or Y?]
How to click on the month above and hide the corresponding date below?

**Comment by kizitonwose** [comment]
I assume you need the same logic used [here](https://github.com/kizitonwose/Calendar/blob/main/docs/View.md#week-view), except you hide the entire month and set the click listener on the month header. See the sample app for how we animate the month.
