### ISSUE TITLE
how can i show the lunar calendar's bellow the number？

### ISSUE THREAD

**Issue by jeff-sun** [kizitonwose/Calendar#545]
### Library information:
 - Version: [2.5.1]
 - View or Compose module: [View]

### Question:
[how can i show the lunar calendar's bellow the number？]
like this
![image](https://github.com/kizitonwose/Calendar/assets/20920804/0b92506e-1a54-44ae-b222-ab7b64af489b)

**Comment by kizitonwose** [comment]
You will need to do some conversion with an external library, as this feature is not built into the e`java.time` package. See [this](https://stackoverflow.com/a/49163559)

**Comment by hoangvuanhdevelopervn** [comment]
Use this
```

 val lunarDay = LunarCoreHelper.convertSolar2Lunar(date.dayOfMonth, date.month.value, 2024, 7.0)
        val solarDate = "${date.dayOfMonth}"
        var lunarDate = "${lunarDay[0]}"
       val lunarMonth = lunarDay[1]
        if (lunarDay[0] == 1) {
          lunarDate = "${lunarDay[0]}/${lunarMonth}"
        }

        val chineseCalendar = ChineseCalendar(convertLocalDateToDate(date))
        val chineseDay = chineseCalendar.get(ChineseCalendar.DAY_OF_MONTH)
        val chineseMonth = chineseCalendar.get(ChineseCalendar.MONTH)
        var lunarDate = "$chineseDay"
        if (chineseDay == 1) {
            lunarDate = "${chineseDay}/${chineseMonth + 1}"
        }
```
        
        ChineseCalendar already have in Android Studio, just implement: import android.icu.util.ChineseCalendar and use them.
        
        Link for LunarCoreHelper: https://github.com/appota/JavaLunarCore/blob/master/lunarcore/src/main/java/com/appota/lunarcore/LunarCoreHelper.java
