### ISSUE TITLE
some suggest

### ISSUE THREAD

**Issue by k849717776** [kizitonwose/Calendar#553]
about rememberCalendarState, some time I need scrollProcess, like float, percent。but it only has isScrollInProgress。
it means i want to do some operation when it scorll maybe  30% 50% 70%。that like CalendarState's visibleItemState or internal listState
but i can't use it

**Comment by kizitonwose** [comment]
The two properties of the LazyListState `firstVisibleItemIndex` and `firstVisibleItemScrollOffset` can be read from the calendar state:

`firstVisibleItemIndex`  => `state.layoutInfo.visibleItemsInfo.firstOrNull()?.index ?: 0`

`firstVisibleItemScrollOffset`  => `state.layoutInfo.visibleItemsInfo.firstOrNull()?.offset ?: 0`

**Comment by k849717776** [comment]
thanks
