### ISSUE TITLE
Maven Repository - Binary for 0.3.2 not available

### ISSUE THREAD

**Issue by gea-rshin** [kizitonwose/Calendar#555]
### Library information:
 - Version: 0.4.3
 - View or Compose module: view

### To Reproduce (if applicable)
1. Add library via `implementation 'com.github.kizitonwose:CalendarView:0.3.2'` in app's build.gradle file
2. App does not build

### Expected behavior (if applicable)
- App should build

### Screenshots? (if applicable)
![image](https://github.com/kizitonwose/Calendar/assets/110079679/7a658361-f22f-453c-a4c4-b1ff6ae8a57a)

### Additional information
- Maven Repository Version Page: https://mvnrepository.com/artifact/com.github.kizitonwose/CalendarView/0.4.3
- Maven Repository Binary Coordinates: https://repository.mulesoft.org/nexus/content/repositories/public/com/github/kizitonwose/CalendarView/0.4.3

Was this library recently released to Maven Central? Did this perhaps break the Maven coordinates for the binaries of specific versions of the library?

**Comment by kizitonwose** [comment]
The library was published to maven central from version 2.0.0. Earlier versions were published to jitpack so you have to add the jitpack maven repository.

```groovy
maven { url "https://jitpack.io" }
```

**Comment by gea-rshin** [comment]
Thank you for the response! Especially so quickly. 

That makes sense, I do have jitpack already included in my project, but I am currently getting the following build error.
`Could not find com.github.kizitonwose:CalendarView:0.3.2`

Perhaps it is my local cache. I'll try again and update results here
Perhaps it is a temporary Jitpack issue

Thanks again for the help 😃

**Comment by gea-rshin** [comment]
@kizitonwose , thanks again for the support but it looks like the AAR file for 0.3.2 can't be found on Jitpack


- https://jitpack.io/#kizitonwose/CalendarView/0.3.2
- https://jitpack.io/com/github/kizitonwose/CalendarView/0.3.2/CalendarView-0.3.2.aar

![image](https://github.com/kizitonwose/Calendar/assets/110079679/e1b927a4-418a-474b-8cda-ca1c44bdb71a)

**Comment by kizitonwose** [comment]
Not sure why that version is missing in JitPack, however, I see that[ 0.3.4](https://jitpack.io/com/github/kizitonwose/CalendarView/0.3.4) is available. Do you mind using that instead? There should be no code changes required.

**Comment by gea-rshin** [comment]
Yeap, sounds good
Thanks again 👍
