### ISSUE TITLE
How to use with API level 25

### ISSUE THREAD

**Issue by snarut** [kizitonwose/Calendar#556]
### Library information:
 - Version: 2.1.0
 - View or Compose module: View

### Question:
How do I use WeekCalendarView with API level 25?
I have problem building my project since some of Calendar's functions use java.time.LocalDate as parameter which only available after API level 26

**Comment by kizitonwose** [comment]
You need to enable [desugar](https://developer.android.com/studio/write/java8-support). Please read the [setup instructions](https://github.com/kizitonwose/Calendar#setup) in the README.
