### ISSUE TITLE
Is grid calendar supported?

### ISSUE THREAD

**Issue by 0guzdemirel** [kizitonwose/Calendar#557]
### Library information:
 - Version: 2.0.0
 - View or Compose module: View

### Question:
Does this library have support for grid looking calendar like this? If so can you help me how to implement that grid looking calendar?
<img width="276" alt="Screenshot 2024-07-11 at 09 59 14" src="https://github.com/kizitonwose/Calendar/assets/108752034/f4aeaf59-368a-4aa2-8bfe-f016ac516092">

**Comment by kizitonwose** [comment]
Duplicate https://github.com/kizitonwose/Calendar/issues/535#issuecomment-2241054447
