### ISSUE TITLE
Failed to generate a build because of the jar is unavailable

### ISSUE THREAD

**Issue by AliRashadPM** [kizitonwose/Calendar#564]
### Library information:
 - Version: 1.1.0 - 2.0.0
 - View or Compose module: [e.g. view]

### Describe the bug**
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsProductionDebug'.
> Could not resolve all files for configuration ':app:productionDebugRuntimeClasspath'.
   > Failed to transform CalendarView-1.1.0.aar (com.github.kizitonwose:CalendarView:1.1.0) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find CalendarView-1.1.0.aar (com.github.kizitonwose:CalendarView:1.1.0).
        Searched in the following locations:
            https://jitpack.io/com/github/kizitonwose/CalendarView/1.1.0/CalendarView-1.1.0.aar

### To Reproduce (if applicable)
1- Trying to generate a build in Bitrise

### Screenshots? (if applicable)
If applicable, add screenshots or screen recordings to help explain the problem.

### Additional information
Add any other information about the bug here.

**Comment by PatrickHum-at** [comment]
+1 to this problem. cc @kizitonwose 

I've also opened an issue on the Jitpack side in case its a problem on their end https://github.com/jitpack/jitpack.io/issues/6400

**Comment by PatrickHum-at** [comment]
For those who are struggling with the same problem, the artifact ID seems to have changed from
CalendarView -> Calendar

Try using com.github.kizitonwose:Calendar:1.1.0 instead.

**Comment by kizitonwose** [comment]
Yep, it's a JitPack issue. Seems their repo has become somewhat unreliable recently. Someone reported a missing artifact a few weeks ago #555

**Comment by kizitonwose** [comment]
Closing this since there's nothing to do on my side.
