### ISSUE TITLE
Does it support selecting months in the calendar?

### ISSUE THREAD

**Issue by JamesGZM** [kizitonwose/Calendar#574]
### Feature
Does it support selecting months in the calendar? I checked the API and there is no content that can be set to click on the month separately

### Tech (if applicable)
I use it in Android XML

**Comment by kizitonwose** [comment]
You can create a [monthViewClass](https://github.com/kizitonwose/Calendar/blob/df2702157db6bdab80a63f31ece1e8f1b942d8ad/sample/src/main/java/com/kizitonwose/calendar/sample/view/Example6Fragment.kt#L30) and set a click listener on that view.

**Comment by JamesGZM** [comment]
> You can create a [monthViewClass](https://github.com/kizitonwose/Calendar/blob/df2702157db6bdab80a63f31ece1e8f1b942d8ad/sample/src/main/java/com/kizitonwose/calendar/sample/view/Example6Fragment.kt#L30) and set a click listener on that view.

I tried using this feature, but I am confused. How do I know which month I clicked on?

**Comment by JamesGZM** [comment]
```kotin
class YearMonthView @Keep constructor(context: Context) : FrameLayout(context) {

    init {
        setOnClickListener {
            val monthTv: TextView? = findViewById(R.id.month_tv)
            toast(monthTv?.text ?: "")
            LogUtils.e(tag)
        }
    }
}
```

I am currently setting the view tag in the bind of the monthly HeaderBinder

**Comment by kizitonwose** [comment]
You can set the tag or keep a field in the view that you update in the bind
