### ISSUE TITLE
Help Needed: Customizing Calendar for my vecka kalender website

### ISSUE THREAD

**Issue by VECKAKALENDAR** [kizitonwose/Calendar#575]
Hi,

I’m integrating the Calendar library into my [veckakalendar](https://veckakalender.se/kalender/) website. I need help with the following:
1. Highlighting specific dates (e.g., Mother's Day) with custom styles.
2. Integrating the calendar into my CMS smoothly.

Any tips or guidance would be greatly appreciated!

**Comment by kizitonwose** [comment]
Please look at the examples and documentation. Highlighting is covered there.
