### ISSUE TITLE
Duplicate class com.kizitonwose.calendar.compose.CalendarDefaults 

### ISSUE THREAD

**Issue by aniluMango** [kizitonwose/Calendar#577]
We intended to utilize the library in both Android and multiplatform projects, but we encountered the following issue while doing so.

Duplicate class com.kizitonwose.calendar.compose.CalendarDefaults found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarDefaultsKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarDefaultsKt$CalendarSnapLayoutInfoProvider$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarInfo found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarItemInfo found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarLayoutInfo found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarMonthsKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarMonthsKt$CalendarMonths$2 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarMonthsKt$CalendarMonths$2$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarMonthsKt$CalendarMonths$2$1$1$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarMonthsKt$CalendarMonths$2$WhenMappings found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarState found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarState$Companion found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.CalendarStateKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.ComposableSingletons$CalendarMonthsKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.ComposableSingletons$CalendarMonthsKt$lambda-1$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.ComposableSingletons$CalendarMonthsKt$lambda-2$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.ContentHeightMode found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.heatmapcalendar.HeatMapCalendarKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.heatmapcalendar.HeatMapCalendarKt$HeatMapCalendarImpl$1$1$1$2 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.heatmapcalendar.HeatMapCalendarState found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.heatmapcalendar.HeatMapCalendarState$Companion found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.heatmapcalendar.HeatMapCalendarStateKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.heatmapcalendar.HeatMapWeek found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.heatmapcalendar.HeatMapWeekHeaderPosition found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.weekcalendar.WeekCalendarItemInfo found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.weekcalendar.WeekCalendarKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.weekcalendar.WeekCalendarKt$WeekCalendarImpl$1$1$2 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.weekcalendar.WeekCalendarLayoutInfo found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.weekcalendar.WeekCalendarState found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.weekcalendar.WeekCalendarState$Companion found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.weekcalendar.WeekCalendarStateKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.ComposableSingletons$YearCalendarMonthsKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.ComposableSingletons$YearCalendarMonthsKt$lambda-1$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.ComposableSingletons$YearCalendarMonthsKt$lambda-2$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.ComposableSingletons$YearCalendarMonthsKt$lambda-3$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.ComposableSingletons$YearCalendarMonthsKt$lambda-4$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarItemInfo found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarLayoutInfo found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt$YearCalendarMonths$2 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt$YearCalendarMonths$2$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt$YearCalendarMonths$2$1$1$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt$YearCalendarMonths$2$1$1$1$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt$YearCalendarMonths$2$1$1$1$1$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt$YearCalendarMonths$2$1$1$1$1$1$1$1 found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarMonthsKt$YearCalendarMonths$2$WhenMappings found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarState found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarState$Companion found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearCalendarStateKt found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.compose.yearcalendar.YearContentHeightMode found in modules compose-2.5.4.aar -> jetified-compose-2.5.4-runtime (com.kizitonwose.calendar:compose:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.CalendarDay found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.CalendarMonth found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.CalendarYear found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.DayPosition found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.ExperimentalCalendarApi found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.ExtensionsKt found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.ExtensionsKt$EntriesMappings found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.OutDateStyle found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.Week found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.WeekDay found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.core.WeekDayPosition found in modules core-2.5.4.jar -> jetified-core-2.5.4 (com.kizitonwose.calendar:core:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.DataStore found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.MonthData found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.MonthDataKt found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.UtilsKt found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.WeekData found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.WeekDataKt found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.WeekDateRange found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.YearDataKt found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)
Duplicate class com.kizitonwose.calendar.data.YearDataKt$EntriesMappings found in modules data-2.5.4.jar -> jetified-data-2.5.4 (com.kizitonwose.calendar:data:2.5.4) and library-release.aar -> jetified-library-release-runtime (com.kizitonwose.calendar:compose-multiplatform-android:2.5.4)

<img width="1470" alt="Screenshot 2024-08-19 at 11 01 25 AM" src="https://github.com/user-attachments/assets/1b8d3956-6bbb-4a61-b587-d8acd447afe6">

**Comment by kizitonwose** [comment]
Please read the [setup](https://github.com/kizitonwose/Calendar#setup) instructions carefully. The compose-multiplatform and compose android modules cannot exist in the same project. If you are building a multiplatform project, the multiplatform module is sufficient, it exposes Android, iOS, wasmJs and Desktop targets.
