### ISSUE TITLE
Question about Calendar switching month height

### ISSUE THREAD

**Issue by DishengYang** [kizitonwose/Calendar#583]
If the height of the day view needs to be adaptive, and you need to reset the height when you switch months what should you do?

**Comment by kizitonwose** [comment]
You can always use the week calendar height to determine the animation height for both week and month calendar. See [this](https://github.com/kizitonwose/Calendar/blob/f0ddb8105b4e4c269bbf18f9e4428570ca4b0d43/sample/src/main/java/com/kizitonwose/calendar/sample/view/Example1Fragment.kt#L217)
