### ISSUE TITLE
SnapPositionInLayout nt found

### ISSUE THREAD

**Issue by TooLazyy** [kizitonwose/Calendar#590]
### Library information:
 - Version: 2.5.x
 - compose

### Describe the bug**
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/foundation/gestures/snapping/SnapPositionInLayout; when using horizontal callendar

compose ui version - 1.6.8

I can see [this issue](https://github.com/kizitonwose/Calendar/issues/576) and [this issue](https://github.com/kizitonwose/Calendar/issues/547) marked as closed, but there's no solution.
I dont wanna to update to compose beta.

Btw, if I create SnapLayoutInfoProvider in my code - it works fine and doest crash. Crash only happens inside the library.

**Comment by kizitonwose** [comment]
The only reason this would be crashing in your code is that another dependency is transitively upgrading your Compose UI version to 1.7. You have to either find this dependency and downgrade it or use a compatible calendar version 2.6.x
