### ISSUE TITLE
Heatmap demo: Can't get vertical scroll working

### ISSUE THREAD

**Issue by zell-mbc** [kizitonwose/Calendar#591]
### Library information:
 - Version: 2.6.0
 - Heatmap Compose
 
### Question:
I just migrated my heatmap chart to your formidable library. Following your heatmap demo I got everything working quite quickly, the last thing missing is that I somehow can't get the Box() holding the heatmap to scroll vertically.
My implementation is very similar to your demo, means, a user can click on a day to show the content of that day at the bottom of the screen. In portrait mode there is sufficient space, in landscape however, things get cut off or won't show at all.

![image](https://github.com/user-attachments/assets/7e0aa723-bbba-467d-8498-4164665905e2)

I tried adding `Modifier.verticalScroll(rememberScrollState())` to the top level Box and also the column below, but somehow nothing seems to work?
```
Box(modifier = Modifier.safeDrawingPadding()) {
            Column(modifier = Modifier.fillMaxSize()) {
                val state = rememberHeatMapCalendarState(
                    startMonth = startDate.yearMonth,
                    endMonth = endDate.yearMonth,
                    firstVisibleMonth = endDate.yearMonth,
                    firstDayOfWeek = firstDayOfWeekFromLocale(),
                )
                HeatMapCalendar(
                …
```
Anyone got an idea what might go wrong here?

**Comment by kizitonwose** [comment]
Repeated the button and put Example 6 in a `verticalScroll` modifier, and it worked without issues. Are you sure you are setting the modifier to the correct layout?

https://github.com/user-attachments/assets/a27cbab9-4194-44fa-b1a0-a62bf7fcebef
