### ISSUE TITLE
Advertisement support: PrivacySandbox-Tools in Calendar library

### ISSUE THREAD

**Issue by zell-mbc** [kizitonwose/Calendar#592]
### Library information:
 - Version: 2.0.6
 - Compose

### Question:
I recently added your HeatMap Calendar to my app and now I am getting app stores flagging my app for advertisement infrastructure.
https://codeberg.org/toz/MediLog/issues/436

Given that I want to stay clear form anything related to ads and tracking there's nothing in my own code. Hence the only change I can think of which may trigger theses scanners is via the addition of your library?
Can you please let me know if there is anything related to advertisement built into your library? And if there is, would you consider offering an add free version?

Thanks

**Comment by kizitonwose** [comment]
Nope, there is nothing ad-related in the library. You can see all the dependencies in the calendar compose module which is used in your app [here](https://github.com/kizitonwose/Calendar/blob/main/compose/build.gradle.kts). It's purely compose and kotlin dependencies in that file.

**Comment by kizitonwose** [comment]
I looked at [the version diff](https://codeberg.org/toz/MediLog/compare/v3.0.5...v3.0.6#diff-d7595319a0658be6f1ed500ad590d42e4b28bc4f) in your repository, you added [this dependency](https://codeberg.org/toz/MediLog/src/branch/master/gradle/libs.versions.toml#L82) which I think is the culprit:
 
`androidx-tools-core = { group = "androidx.privacysandbox.tools", name = "tools-core", version.ref = "toolsCoreVersion" }`

**Comment by zell-mbc** [comment]
Thank you very much for looking into this, I feel really stupid now :-(
But to be honest, I can't remember adding that library.
Well, I removed that lib, my app compiles and I am able to keep your wonderful calendar. All good in the end :-)
