### ISSUE TITLE
KMP Cold not resolve new 2.6.0 version of librarry

### ISSUE THREAD

**Issue by kopoh** [kizitonwose/Calendar#593]
### Library information:
 - Version: [2.6.0]
 - KMP project (kotlin-2.0.20 + CM-1.7.0)

### Describe the bug

I attempted to update the library from version 2.6.0-alpha01 to the stable release 2.6.0. However, after updating, the library does not function as expected, and several functionalities stopped working.

### Expected behavior

After updating to the stable version 2.6.0, I expect the library to work properly with all existing functionality, without breaking any parts of my project.

### Screenshots
<img width="1342" alt="изображение" src="https://github.com/user-attachments/assets/8e4ef70e-7ea6-483d-98d1-f17c2762e9d0">

### Steps to reproduce

1.	Update the library from 2.6.0-alpha01 to 2.6.0.
2.	Build and run the project.
3.	Observe the issues (mention any specific errors or logs if available).

### Additional information

[On maven repository](https://mvnrepository.com/artifact/com.kizitonwose.calendar/compose-multiplatform) latest version 2.6.0-beta01, instead of 2.6.0 like on github releases

**Comment by kizitonwose** [comment]
2.6.0 is the Android project. The latest KMP release is 2.6.0-beta01. See the badge in the README

**Comment by kopoh** [comment]
Oh, I'm sorry, I really missed this information. I hope the new version for KMP will be released as soon as possible!
Thank you very much for your work
<img width="785" alt="изображение" src="https://github.com/user-attachments/assets/90a3524d-ff51-40a3-b4a0-cc975fbe19b5">
